import crypto from "node:crypto";
import type pg from "pg";
import { screenshotKey } from "../storage/keys.js";
import type { ObjectStorage } from "../storage/client.js";
import type { ScreenshotContentType } from "./retention.js";
import type { JobScreenshot, JobScreenshotContent } from "./types.js";

interface ScreenshotRow {
  id: string;
  job_id: string;
  project_id: string;
  step_name: string;
  content_type: ScreenshotContentType;
  byte_size: number;
  expires_at: Date;
  purged_at: Date | null;
  created_at: Date;
  storage_backend: StorageBackend;
  object_key: string | null;
}

type StorageBackend = "postgres" | "object";

interface ScreenshotContentRow extends ScreenshotRow {
  data: Buffer | null;
}

/**
 * The columns a metadata read returns. Spelled once so the list and the
 * content read cannot drift — adding a column to one and forgetting the other
 * would surface as a missing field at runtime, not as a type error.
 */
const metadataColumns = `
  id, job_id, project_id, step_name, content_type, byte_size,
  expires_at, purged_at, created_at, storage_backend, object_key
`;

function mapScreenshot(row: ScreenshotRow): JobScreenshot {
  return {
    id: row.id,
    jobId: row.job_id,
    projectId: row.project_id,
    stepName: row.step_name,
    contentType: row.content_type,
    byteSize: row.byte_size,
    expiresAt: row.expires_at,
    purgedAt: row.purged_at,
    createdAt: row.created_at,
  };
}

/**
 * Issue #22's storage for per-step test-run screenshots.
 *
 * Mirrors `JobRecordingRepository` deliberately — same tombstone discipline,
 * same "bytes in Postgres for now" posture, same read paths that never touch
 * `data` unless the caller asked for bytes. The differences are the ones the
 * migration documents: keyed by `id` (a step name is free text, not a URL
 * segment), upserted on `(job_id, step_name)` (one screenshot per step), and
 * bounded per *job* as well as per file.
 *
 * The object-storage question from issue #30 arrived here at exactly the same two
 * methods (`upsert`'s payload and `findContent`) as it does for recordings,
 * because both classes were built with that swap in mind — and that prediction
 * held: the swap below is the same shape as `JobRecordingRepository`'s, down to
 * the write-object-then-row ordering and the per-row backend dispatch. The one
 * asymmetry is deliberate and documented: `purgeExpired` here tombstones
 * against `id` rather than `job_id`, because a job has many screenshots.
 */
export class JobScreenshotRepository {
  constructor(
    private readonly db: pg.Pool,
    private readonly storage: ObjectStorage | null = null,
  ) {}

  /**
   * Stores (or replaces) one step's screenshot.
   *
   * Upsert on `(job_id, step_name)` rather than insert: the Orchestrator's
   * upload is a best-effort side-channel with no exactly-once guarantee — the
   * same posture `JobRecordingRepository.upsert` takes, and ADR 023's usage
   * report before it — so a retried post must replace rather than duplicate the
   * artifact. `purged_at = NULL` on conflict means a re-upload also replaces a
   * tombstone, which is correct if retention was raised and the artifact
   * re-collected.
   *
   * `project_id` is taken from the job row by the caller rather than trusted
   * from the request, matching the deploy ledger's rule: a caller cannot
   * attribute an artifact to a project it does not belong to.
   */
  async upsert(input: {
    jobId: string;
    projectId: string;
    stepName: string;
    contentType: ScreenshotContentType;
    data: Buffer;
    expiresAt: Date;
  }): Promise<JobScreenshot> {
    const backend: StorageBackend = this.storage ? "object" : "postgres";
    const key = this.storage
      ? screenshotKey({
          projectId: input.projectId,
          jobId: input.jobId,
          // The row's id is generated by the database, so a key built before the
          // insert cannot use it. The natural key *is* `(job_id, step_name)` —
          // the same pair the upsert conflicts on — and a step name is
          // URL-safe once encoded, which `storage/keys.ts` does.
          screenshotId: stepKeySegment(input.stepName),
          contentType: input.contentType,
        })
      : null;

    if (this.storage && key) {
      await this.storage.putObject({
        key,
        body: input.data,
        contentType: input.contentType,
      });
    }

    try {
      const result = await this.db.query<ScreenshotRow>(
        `INSERT INTO job_screenshots
           (job_id, project_id, step_name, content_type, byte_size, data, expires_at,
            purged_at, storage_backend, object_key)
         VALUES ($1, $2, $3, $4, $5, $6, $7, NULL, $8, $9)
         ON CONFLICT (job_id, step_name) DO UPDATE SET
           content_type    = EXCLUDED.content_type,
           byte_size       = EXCLUDED.byte_size,
           data            = EXCLUDED.data,
           expires_at      = EXCLUDED.expires_at,
           purged_at       = NULL,
           storage_backend = EXCLUDED.storage_backend,
           object_key      = EXCLUDED.object_key
         RETURNING ${metadataColumns}`,
        [
          input.jobId,
          input.projectId,
          input.stepName,
          input.contentType,
          input.data.byteLength,
          backend === "postgres" ? input.data : null,
          input.expiresAt,
          backend,
          key,
        ],
      );
      return mapScreenshot(result.rows[0]!);
    } catch (error) {
      if (this.storage && key) {
        try {
          await this.storage.deleteObject(key);
        } catch (cleanupError) {
          console.error(
            `failed to clean up object ${key} after a failed screenshot insert: ` +
              `${String(cleanupError)} — this object is now unreferenced`,
          );
        }
      }
      throw error;
    }
  }

  /**
   * One run's screenshots, oldest first — report order, so a caller can line
   * them up with the steps they annotate without re-sorting.
   *
   * Metadata only; never pulls bytes. Tombstoned rows are included on purpose:
   * a purged screenshot must still be *listed*, so the UI can say it existed and
   * was reclaimed rather than showing nothing where a step had one.
   */
  async listForJob(jobId: string, limit = 200): Promise<JobScreenshot[]> {
    const result = await this.db.query<ScreenshotRow>(
      `SELECT ${metadataColumns}
         FROM job_screenshots
        WHERE job_id = $1
        ORDER BY created_at ASC, step_name ASC
        LIMIT $2`,
      [jobId, limit],
    );
    return result.rows.map(mapScreenshot);
  }

  /** A single screenshot's metadata, used to authorize a content read. */
  async findByIdForJob(jobId: string, screenshotId: string): Promise<JobScreenshot | null> {
    const result = await this.db.query<ScreenshotRow>(
      `SELECT ${metadataColumns}
         FROM job_screenshots
        WHERE job_id = $1 AND id = $2`,
      [jobId, screenshotId],
    );
    const row = result.rows[0];
    return row ? mapScreenshot(row) : null;
  }

  /**
   * The bytes, for the download path only. Returns the row even when `data` is
   * null, so the caller can distinguish a purged artifact (row present, no
   * bytes) from an absent one (no row) and answer 410 rather than 404.
   */
  async findContent(
    jobId: string,
    screenshotId: string,
  ): Promise<JobScreenshotContent | null> {
    const result = await this.db.query<ScreenshotContentRow>(
      `SELECT ${metadataColumns}, data
         FROM job_screenshots
        WHERE job_id = $1 AND id = $2`,
      [jobId, screenshotId],
    );
    const row = result.rows[0];
    if (!row) return null;

    if (row.storage_backend === "postgres" || row.object_key === null) {
      return { ...mapScreenshot(row), data: row.data };
    }
    if (row.purged_at !== null) {
      return { ...mapScreenshot(row), data: null };
    }

    const bytes = await this.storage!.getObject(row.object_key);
    if (bytes === null) {
      console.error(
        `screenshot ${screenshotId} for job ${jobId} is recorded as stored at ` +
          `${row.object_key}, but that object does not exist — the artifact is unrecoverable`,
      );
    }
    return { ...mapScreenshot(row), data: bytes };
  }

  /**
   * How many screenshots a job already has, tombstones included.
   *
   * The upsert's `ON CONFLICT` replaces rather than adds, so this counts
   * *distinct steps* — which is the quantity the per-job cap is about. Counting
   * tombstones keeps the cap monotone: a job that once had 50 screenshots and
   * had them purged does not silently get 50 more.
   */
  async countForJob(jobId: string): Promise<number> {
    const result = await this.db.query<{ count: string }>(
      `SELECT COUNT(*)::text AS count FROM job_screenshots WHERE job_id = $1`,
      [jobId],
    );
    return Number(result.rows[0]?.count ?? 0);
  }

  /**
   * Reclaims the bytes of every screenshot past its expiry, keeping the rows as
   * tombstones. Returns how many artifacts were purged.
   *
   * `expires_at <= NOW()` mirrors the shared `artifactState` predicate exactly —
   * the same rule written twice, once in SQL for the sweep and once in
   * TypeScript for a read, which is precisely why that rule lives in one shared
   * module. This is the SQL half; `shared/artifacts.ts` is the other.
   *
   * `LIMIT`ed and idempotent: the partial index only covers rows still holding
   * bytes, so a second pass finds nothing, and a backlog drains over successive
   * ticks rather than in one long transaction.
   */
  async purgeExpired(limit = 100): Promise<number> {
    const candidates = await this.db.query<{
      id: string;
      storage_backend: StorageBackend;
      object_key: string | null;
    }>(
      `SELECT id, storage_backend, object_key
         FROM job_screenshots
        WHERE (data IS NOT NULL OR object_key IS NOT NULL)
          AND expires_at <= NOW()
        ORDER BY expires_at ASC
        LIMIT $1`,
      [limit],
    );
    if (candidates.rows.length === 0) return 0;

    const reclaimableInDatabase: string[] = [];
    const reclaimedInStorage: string[] = [];

    // Same split as `JobRecordingRepository.purgeExpired`, for the same reason:
    // a database tombstone needs nothing external to succeed, an object delete
    // does, and a batch must not let the second's failure suppress the first's
    // progress. See that method for the full argument.
    for (const row of candidates.rows) {
      if (row.storage_backend === "postgres") {
        reclaimableInDatabase.push(row.id);
        continue;
      }
      if (!this.storage || row.object_key === null) {
        console.error(
          `screenshot ${row.id} is in object storage at ${row.object_key}, ` +
            `but no object storage is configured — leaving it reclaimable`,
        );
        continue;
      }
      try {
        await this.storage.deleteObject(row.object_key);
        reclaimedInStorage.push(row.id);
      } catch (error) {
        console.error(
          `failed to delete object ${row.object_key} for screenshot ${row.id}: ` +
            `${String(error)} — leaving the row reclaimable and retrying next pass`,
        );
      }
    }

    let purged = 0;
    if (reclaimableInDatabase.length > 0) {
      const result = await this.db.query(
        `UPDATE job_screenshots SET data = NULL, purged_at = NOW()
          WHERE id = ANY($1::uuid[])`,
        [reclaimableInDatabase],
      );
      purged += result.rowCount ?? 0;
    }
    if (reclaimedInStorage.length > 0) {
      const result = await this.db.query(
        `UPDATE job_screenshots SET purged_at = NOW()
          WHERE id = ANY($1::uuid[])`,
        [reclaimedInStorage],
      );
      purged += result.rowCount ?? 0;
    }
    return purged;
  }
}

/**
 * A step name as a single path segment inside the key: sanitised for
 * readability, then disambiguated with a short digest of the *exact* name.
 *
 * A step name is free text from the test markdown's `##` headings, so it can
 * contain `/`. Embedded raw that would add a level to the object path, and
 * simply replacing the separators is not enough on its own: `a/b` and `a_b`
 * would then share one key, so two distinct steps of the same job would
 * silently overwrite each other's bytes. Appending a digest of the original
 * name makes the mapping injective, and truncating it to eight hex characters
 * is safe because the only names it must distinguish are two steps of one job,
 * where a collision means two specific headings rather than a birthday attack.
 *
 * The key being *derived* rather than *authoritative* is what keeps this from
 * mattering more: an object is only ever addressed through its row, so this
 * function decides where bytes are written and read back, never which artifact
 * a user asked for.
 */
export function stepKeySegment(stepName: string): string {
  const readable = stepName.replace(/[/\\]/g, "_").slice(0, 80);
  const digest = crypto.createHash("sha256").update(stepName).digest("hex").slice(0, 8);
  return `${readable}-${digest}`;
}
