import { Router } from "express";
import { z } from "zod";
import { requireInternalApiToken } from "../secrets/internal-auth.js";
import { routeParam } from "../shared/route-param.js";
import { isUuid } from "../shared/uuid.js";
import type { FeatureActionItemRepository } from "../features/action-items-repository.js";
import type { FeatureRepository } from "../features/repository.js";
import type { DesignRepository } from "../designs/repository.js";
import type { JobEventRepository } from "./events-repository.js";
import type { JobRepository } from "./repository.js";
import type { JobKind } from "./types.js";
import type { ProjectRepository } from "../projects/repository.js";
import type { TestRepository } from "../tests/repository.js";
import type { TestRunReportRepository } from "../tests/reports-repository.js";
import { AGENT_JOB_KINDS, type AgentJobKind, type ModelConfigSource } from "../model-config/types.js";
import {
  resolveModelConfigSource,
  type ModelConfigResolutionDeps,
} from "../secrets/model-config.js";
import type { JobUsageRepository } from "../usage/repository.js";
import { NOOP_LIVE_PUBLISHER, type LivePublisher } from "../live/deltas.js";
import { summarizeGrillTranscript } from "./grill-context.js";
import { evaluateTestingGate } from "../features/testing-gate-runner.js";

const actionItemSchema = z.object({
  type: z.enum(["secret_request", "design_grill", "subtask_feature", "test_request"]),
  description: z.string(),
  secretKey: z.string().optional(),
  draftTestMarkdown: z.string().optional(),
});

const designSnapshotSchema = z
  .record(z.string().trim().min(1).max(256), z.string().max(500_000))
  .superRefine((snapshot, ctx) => {
    if (Object.keys(snapshot).length === 0) {
      ctx.addIssue({ code: "custom", message: "Design snapshots cannot be empty" });
    }
    if (Object.keys(snapshot).length > 100) {
      ctx.addIssue({ code: "custom", message: "Design snapshots may contain at most 100 files" });
    }
    for (const path of Object.keys(snapshot)) {
      if (
        path.startsWith("/") ||
        path.includes("\\") ||
        path.split("/").some((part) => part === ".." || part === ".")
      ) {
        ctx.addIssue({ code: "custom", message: "Design snapshot paths must be safe relative paths" });
        break;
      }
    }
  });

const jobEventSchema = z.object({
  type: z.enum([
    "agent_text",
    "ask_user",
    "submit_adr",
    "run_failed",
    "run_cancelled",
    "submit_build_result",
    "run_started",
    "request_action_item",
    "submit_review",
    "report_test_step",
    "submit_test_report",
    "update_design_preview",
    "submit_design",
  ]),
  question: z.string().optional(),
  markdown: z.string().optional(),
  message: z.string().optional(),
  status: z.string().optional(),
  prUrl: z.string().optional(),
  summary: z.string().optional(),
  comment: z.string().optional(),
  // submit_review (ADR 015 item 14-16): the internal Agentic Review verdict.
  verdict: z.enum(["approved", "changes_requested"]).optional(),
  // ADR 015 item 4: submit_adr carries the Action Items batch generated by
  // this spec_grill run (optional).
  actionItems: z.array(actionItemSchema).optional(),
  testName: z.string().optional(),
  testStatus: z.enum(["pass", "fail"]).optional(),
  testDetails: z.string().optional(),
  screenshotPath: z.string().optional(),
  passed: z.number().int().nonnegative().optional(),
  failed: z.number().int().nonnegative().optional(),
  skipped: z.number().int().nonnegative().optional(),
  total: z.number().int().nonnegative().optional(),
  coveragePercent: z.number().min(0).max(100).optional(),
  failingTests: z.array(z.string()).optional(),
  recordingPath: z.string().optional(),
  snapshot: designSnapshotSchema.optional(),
  hasDesignSurface: z.boolean().optional(),
}).superRefine((event, ctx) => {
  if (event.type === "report_test_step" && (!event.testName || !event.testStatus)) {
    ctx.addIssue({
      code: "custom",
      message: "Test step reports require testName and testStatus",
    });
  }
  if (
    event.type === "submit_test_report" &&
    (event.passed === undefined || event.failed === undefined || !event.summary)
  ) {
    ctx.addIssue({
      code: "custom",
      message: "Test reports require passed, failed, and summary",
    });
  }
  if (
    event.type === "submit_test_report" &&
    event.total !== undefined &&
    event.passed !== undefined &&
    event.failed !== undefined &&
    event.total < event.passed + event.failed + (event.skipped ?? 0)
  ) {
    ctx.addIssue({
      code: "custom",
      message: "Test report total cannot be less than its result counts",
    });
  }
  if (
    (event.type === "update_design_preview" || event.type === "submit_design") &&
    !event.snapshot
  ) {
    ctx.addIssue({
      code: "custom",
      message: "Design events require a full path-to-content snapshot",
    });
  }
  if (event.type === "submit_review" && (!event.verdict || (!event.comment && !event.summary))) {
    ctx.addIssue({
      code: "custom",
      message: "Review events require a verdict and comment",
    });
  }
});

const requestedActionItemSchema = z.object({
  type: z.string(),
  description: z.string(),
});

/**
 * ADR 019 item 13: one streaming chunk of assistant text.
 *
 * Deliberately NOT a member of `jobEventSchema`'s enum, and deliberately its own
 * schema rather than a widened enum with a runtime exclusion. The stored-event
 * enum stays authoritative for what can become a `job_events` row, so
 * "`agent_text_delta` is relayed but never stored" is enforced by the shape of
 * the validation rather than by a branch someone could later reorder.
 *
 * `message` is the delta text (the same field the Orchestrator already uses for
 * prose), bounded because it travels through a `pg_notify` payload whose hard
 * limit is 8000 bytes — a genuine chunk is a handful of bytes, so this only
 * rejects a producer that is not actually streaming.
 */
const jobEventDeltaSchema = z.object({
  type: z.literal("agent_text_delta"),
  message: z.string().min(1).max(4_000),
});

/**
 * ADR 023: the accounting block the Orchestrator reads from Pi's own
 * get_session_stats at the end of a job's session. Non-negative throughout —
 * Pi cannot legitimately report negative usage, so a negative value is a bug
 * upstream and is rejected rather than stored.
 */
const jobUsageSchema = z.object({
  modelId: z.string().trim().max(256).optional(),
  inputTokens: z.number().int().nonnegative(),
  outputTokens: z.number().int().nonnegative(),
  cacheReadTokens: z.number().int().nonnegative(),
  cacheWriteTokens: z.number().int().nonnegative(),
  totalTokens: z.number().int().nonnegative(),
  costUsd: z.number().nonnegative().nullable().optional(),
  durationMs: z.number().int().nonnegative().nullable().optional(),
});

/**
 * Accepts curated events the Orchestrator relays from a running job's Pi
 * RPC session (ADR 006 items 7-8) and persists them — the only place job
 * events enter the API. Read-side (WebSocket relay to the Web app,
 * notifications) is a tracked follow-up.
 */
export function createJobsInternalRouter(deps: {
  jobEvents: JobEventRepository;
  jobs: JobRepository;
  features: FeatureRepository;
  actionItems: FeatureActionItemRepository;
  tests: TestRepository;
  testRunReports: TestRunReportRepository;
  projects: ProjectRepository;
  designs: DesignRepository;
  usage: JobUsageRepository;
  modelConfig: ModelConfigResolutionDeps;
  /**
   * ADR 019 item 13's streaming-delta relay. Optional so the many tests that
   * build this router without caring about the live path keep working, and so a
   * deployment with the relay switched off can simply not pass one.
   */
  live?: LivePublisher;
}): Router {
  const router = Router();
  const live = deps.live ?? NOOP_LIVE_PUBLISHER;

  /**
   * ADR 023: records a finished job's token/cost accounting.
   *
   * Scope is derived entirely from the stored job, never taken from the
   * request body: the caller is the Orchestrator reporting on a job it just
   * ran, so letting it name the project or the tier would make the usage table
   * assertable from outside rather than observed. The body carries only the
   * accounting itself.
   *
   * Not written to the audit trail: ADR 028 item 7 already scopes out
   * `/internal/*` Orchestrator-driven writes, each of which is a job outcome
   * the API itself just orchestrated rather than a human action.
   */
  router.post(
    "/jobs/:jobId/usage",
    requireInternalApiToken,
    async (req, res) => {
      const jobId = routeParam(req.params.jobId);
      if (!isUuid(jobId)) {
        res.status(404).json({ error: "Job not found" });
        return;
      }

      const parsed = jobUsageSchema.safeParse(req.body);
      if (!parsed.success) {
        res.status(400).json({ error: parsed.error.issues[0]?.message ?? "Invalid usage" });
        return;
      }

      const job = await deps.jobs.findById(jobId);
      if (!job) {
        res.status(404).json({ error: "Job not found" });
        return;
      }

      const attribution = await resolveUsageAttribution(deps, job);

      const usage = await deps.usage.upsert({
        jobId: job.id,
        projectId: job.projectId,
        jobKind: job.kind,
        modelId: parsed.data.modelId ?? null,
        modelConfigSource: attribution.source,
        providerName: attribution.providerName,
        inputTokens: parsed.data.inputTokens,
        outputTokens: parsed.data.outputTokens,
        cacheReadTokens: parsed.data.cacheReadTokens,
        cacheWriteTokens: parsed.data.cacheWriteTokens,
        totalTokens: parsed.data.totalTokens,
        costUsd: parsed.data.costUsd ?? null,
        durationMs: parsed.data.durationMs ?? null,
      });

      res.status(201).json({ id: usage.jobId });
    },
  );


  router.post(
    "/jobs/:jobId/events",
    requireInternalApiToken,
    async (req, res) => {
      const jobId = routeParam(req.params.jobId);
      if (!isUuid(jobId)) {
        res.status(404).json({ error: "Job not found" });
        return;
      }

      // ADR 019 item 13: streaming text deltas are relayed, never stored, so this
      // is checked BEFORE the stored-event schema — otherwise the enum would
      // reject the type and no delta would ever be relayed at all.
      //
      // The scope is derived from the stored job rather than taken from the
      // body, matching the usage route above: letting the caller name the
      // feature would make the routing of one feature's text to another
      // feature's subscribers assertable from outside.
      const delta = jobEventDeltaSchema.safeParse(req.body);
      if (delta.success) {
        await publishDelta(deps, live, jobId, delta.data.message);
        // 202, not 201: nothing was created. The caller cannot tell the
        // difference between a relayed delta and a dropped one, and that is
        // intended — deltas are best-effort and an error would report something
        // the agent could not act on.
        res.status(202).json({});
        return;
      }

      const parsed = jobEventSchema.safeParse(req.body);
      if (!parsed.success) {
        res.status(400).json({ error: parsed.error.issues[0]?.message ?? "Invalid event" });
        return;
      }
      if (parsed.data.type === "update_design_preview" || parsed.data.type === "submit_design") {
        const job = await deps.jobs.findById(jobId);
        if (job?.kind !== "design_grill") {
          res.status(400).json({ error: "Design events require a design_grill job" });
          return;
        }
        const prefix = job.designSlug ? `designs/${job.designSlug}/` : null;
        if (prefix && parsed.data.snapshot && Object.keys(parsed.data.snapshot).some((path) => !path.startsWith(prefix))) {
          res.status(400).json({ error: "Design snapshot contains a path outside its design folder" });
          return;
        }
      }
      if (parsed.data.type === "submit_review") {
        const job = await deps.jobs.findById(jobId);
        if (job?.kind !== "agentic_review") {
          res.status(400).json({ error: "Review events require an agentic_review job" });
          return;
        }
      }

      let event;
      try {
        event = await deps.jobEvents.create({
          jobId,
          ...parsed.data,
          message:
            parsed.data.type === "report_test_step"
              ? `${parsed.data.testName ?? "Test step"}: ${parsed.data.testStatus ?? "unknown"}`
              : parsed.data.message,
          summary:
            parsed.data.type === "submit_test_report"
              ? parsed.data.summary ?? ""
              : parsed.data.type === "submit_review"
                ? parsed.data.comment ?? parsed.data.summary
                : parsed.data.summary,
          actionItems: parsed.data.actionItems,
          snapshot: parsed.data.snapshot,
        });
      } catch (error) {
        console.error(`failed to record event for job ${jobId}:`, error);
        res.status(500).json({ error: "Failed to record job event" });
        return;
      }

      await syncFeatureState(deps, jobId, parsed.data);
      res.status(201).json({ id: event.id });
    },
  );

  return router;
}

/**
 * Relays one streaming delta to a feature's subscribers (ADR 019 item 13).
 *
 * Never throws and never fails the request: the delta is ephemeral, the client
 * already has a REST catch-up path, and the authoritative text still arrives as
 * `agent_text`. A failure here is logged so it is visible without being
 * propagated to a caller that has no way to act on it.
 *
 * A job with no `feature_id` (ADR 014's project-scoped `design_grill`) has no
 * feature topic to route to and is dropped, exactly as the stored-event relay
 * drops one.
 */
async function publishDelta(
  deps: { jobs: JobRepository },
  live: LivePublisher,
  jobId: string,
  text: string,
): Promise<void> {
  try {
    const job = await deps.jobs.findById(jobId);
    if (!job || !job.featureId) return;
    await live.publishDelta({ featureId: job.featureId, jobId, text });
  } catch (error) {
    console.error(`failed to relay event delta for job ${jobId}:`, error);
  }
}

/**
 * Reacts to the event just persisted by updating the feature it belongs to
 * (ADR 006 items 10-11; ADR 010 item 9): `ask_user` sets
 * `awaiting_user_input`, so the API/Web app can tell a grill is paused on a
 * human. `submit_adr` is spec_grill's successful terminal event: it stores
 * the submitted markdown and moves the feature `draft` -> `spec_ready`
 * (`FeatureRepository.setSpecReady`, which also clears
 * `awaiting_user_input` itself). `submit_build_result` is feature_build's
 * single terminal event, carrying its own outcome in `status`: `"success"`
 * moves the feature to `testing`, persists the opened PR's URL, and dispatches
 * one agentic `test_run` per enabled test and one script job per
 * structure-standard test script
 * (`FeatureRepository.setTesting`); `"failure"` is handled exactly like
 * `run_failed` below. `run_failed`/`run_cancelled` are the run's
 * unsuccessful terminal events: each clears `awaiting_user_input` (so a job
 * that stops — dies, or is deliberately cancelled, ADR 006 item 13 — while
 * still waiting on a reply doesn't leave the flag stuck true forever) and
 * moves the feature to `failed`/`cancelled` respectively (ADR 007 item 8's
 * retry-grill route depends on a `project_init` feature actually reaching
 * `failed`, not staying on `draft` forever) — without this, the Web app has
 * no way to tell a grill died. feature_build never sets
 * `awaiting_user_input` true in the first place (its implement skill has no
 * ask_user tool, ADR 010), so `submit_build_result` doesn't touch it either
 * way, unlike run_failed/run_cancelled which unconditionally clear it.
 * `run_started` (ADR 011) is synthesized by the Orchestrator the moment a
 * job's pod is up, for both job kinds uniformly - `setRunning`'s own
 * `WHERE status = 'queued'` guard is what makes it a no-op for spec_grill
 * (whose feature sits in `draft`, not `queued`) without any job-kind check
 * here.
 *
 * Best-effort: a failure here doesn't undo the 201 already sent for the
 * event itself, since the event was persisted successfully regardless.
 */
async function syncFeatureState(
  deps: {
    jobEvents: JobEventRepository;
    jobs: JobRepository;
    features: FeatureRepository;
    actionItems: FeatureActionItemRepository;
    tests: TestRepository;
    testRunReports: TestRunReportRepository;
    projects: ProjectRepository;
    designs: DesignRepository;
  },
  jobId: string,
  event: z.infer<typeof jobEventSchema>,
): Promise<void> {
  if (
    event.type !== "ask_user" &&
    event.type !== "run_failed" &&
    event.type !== "run_cancelled" &&
    event.type !== "submit_adr" &&
    event.type !== "submit_build_result" &&
    event.type !== "run_started" &&
    event.type !== "request_action_item" &&
    event.type !== "submit_review" &&
    event.type !== "report_test_step" &&
    event.type !== "submit_test_report" &&
    event.type !== "update_design_preview" &&
    event.type !== "submit_design"
  ) {
    return;
  }
  try {
    const job = await deps.jobs.findById(jobId);
    if (
      (event.type === "update_design_preview" || event.type === "submit_design") &&
      job?.kind !== "design_grill"
    ) {
      return;
    }
    if (event.type === "submit_design") {
      // ADR 020 item 4: this is the moment the design becomes committed and
      // worth browsing — `submit_design` is the skill's own finalize step,
      // which has already committed `designs/<slug>/` and opened the draft PR.
      // Keyed by (project_id, slug) and upserted, so it also repairs a design
      // whose index row was never written.
      if (job && job.designSlug && job.designName) {
        try {
          await deps.designs.finalize({
            projectId: job.projectId,
            name: job.designName,
            slug: job.designSlug,
            jobId: job.id,
            prUrl: event.prUrl ?? null,
          });
        } catch (error) {
          console.error(`failed to finalize design for job ${jobId}:`, error);
        }
      }
      if (event.snapshot && deps.actionItems.resolveDesignSession) {
        await deps.actionItems.resolveDesignSession(jobId, event.snapshot);
      }
      return;
    }
    if (event.type === "update_design_preview" || !job?.featureId) {
      return;
    }
    if (event.type === "run_started") {
      await deps.features.setRunning(job.featureId);
      return;
    }
    if (event.type === "submit_adr") {
      await deps.features.setSpecReady(job.featureId, event.markdown ?? "");
      if (event.hasDesignSurface !== undefined && deps.projects.setHasDesignSurface) {
        const feature = await deps.features.findById(job.projectId, job.featureId);
        if (feature?.featureType === "project_init") {
          await deps.projects.setHasDesignSurface(job.projectId, event.hasDesignSurface);
        }
      }
      // ADR 015 item 4: persist this spec_grill run's Action Items batch,
      // generated once at the draft -> spec_ready transition.
      if (event.actionItems && event.actionItems.length > 0) {
        const actionItems = [];
        for (const item of event.actionItems) {
          let subtaskFeatureId: string | null = null;
          if (item.type === "subtask_feature" && deps.features.createSubtask) {
            const subtask = await deps.features.createSubtask({
              projectId: job.projectId,
              parentFeatureId: job.featureId,
              title: item.description,
            });
            await deps.jobs.create({
              projectId: job.projectId,
              kind: "spec_grill",
              featureId: subtask.id,
            });
            subtaskFeatureId = subtask.id;
          }
          actionItems.push({
            type: item.type,
            description: item.description,
            secretKey: item.secretKey,
            draftTestMarkdown: item.draftTestMarkdown,
            subtaskFeatureId,
          });
        }
        await deps.actionItems.createMany(
          job.featureId,
          actionItems,
        );
      }
      return;
    }
    if (event.type === "submit_build_result") {
      if (event.status === "success") {
        // ADR 015 item 3: Testing starts the instant a build succeeds; the
        // feature no longer jumps straight to in_review.
        const feature = await deps.features.findById(job.projectId, job.featureId);
        const updated = event.prUrl
          ? await deps.features.setTesting(job.featureId, event.prUrl)
          : await deps.features.setTesting(job.featureId);
        if (!updated || !feature) return;

        try {
          const enabledTests = await deps.tests.listEnabledByProject(job.projectId);
          if (await deps.jobs.hasActiveFeatureTestRuns(job.featureId)) return;
          const ref = feature.branchName ?? `yggdrasil/${feature.slug}-${feature.id}`;
          for (const test of enabledTests) {
            await deps.jobs.create({
              projectId: job.projectId,
              kind: "test_run",
              featureId: job.featureId,
              testId: test.id,
              ref,
              trigger: "feature",
            });
          }
          // The presence of test-unit.sh/test-integration.sh in the checked
          // out feature branch is the group's toggle (ADR 015 item 10).
          // Dispatch both probes here; the runner reports a missing script as
          // an empty, skipped group, so the API never needs to parse a repo or
          // maintain a second project-level setting.
          for (const testGroup of ["unit", "integration"] as const) {
            await deps.jobs.create({
              projectId: job.projectId,
              kind: "script_test_run",
              featureId: job.featureId,
              testGroup,
              ref,
              trigger: "feature",
            });
          }
        } catch (error) {
          await deps.features.updateStatus(job.featureId, "failed");
          throw error;
        }
      } else {
        await deps.features.updateStatus(job.featureId, "failed");
      }
      return;
    }
    if (event.type === "report_test_step") {
      if (job.kind !== "test_run") return;
      if (!event.testName || !event.testStatus) return;
      await deps.testRunReports.upsertStep({
        jobId,
        name: event.testName,
        status: event.testStatus,
        details: event.testDetails,
        screenshotPath: event.screenshotPath,
      });
      return;
    }
    if (event.type === "submit_test_report") {
      if (job.kind !== "test_run" && job.kind !== "script_test_run") return;
      if (
        event.passed === undefined ||
        event.failed === undefined ||
        event.summary === undefined
      ) {
        return;
      }
      const skipped = event.skipped ?? 0;
      const total = event.total ?? event.passed + event.failed + skipped;
      await deps.testRunReports.upsertReport({
        jobId,
        passed: event.passed,
        failed: event.failed,
        skipped,
        total,
        coveragePercent: event.coveragePercent,
        failingTests: event.failingTests,
        summary: event.summary,
        recordingPath: event.recordingPath,
      });
      // Issue #40: the gate decides whether the *runs* are done, not whether
      // every one of them submitted a report. The old check bailed while any run
      // lacked one, so a run that never reported (a container that never started)
      // blocked the feature in `testing` forever.
      await evaluateTestingGate(deps, job.projectId, job.featureId);
      return;
    }
    if (event.type === "request_action_item") {
      // ADR 015 item 7-8: feature_build kicked back to Spec. Structurally
      // distinct from a crash (which stays `failed`, ADR 012): the `draft` ->
      // fresh spec_grill run is seeded with the prior context, and the old
      // Action Item batch is cleared so the new run's submit_adr regenerates
      // it cleanly.
      const feature = await deps.features.findById(job.projectId, job.featureId);
      const transcript =
        (await deps.jobEvents.listSpecGrillByFeature?.(job.featureId)) ?? [];
      const designSnapshots =
        (await deps.actionItems.listResolvedDesignSnapshots?.(job.featureId)) ?? [];
      await deps.features.updateStatus(job.featureId, "draft");
      await deps.actionItems.clearForFeature(job.featureId);
      await deps.jobs.create({
        projectId: job.projectId,
        kind: "spec_grill",
        featureId: job.featureId,
        specContext: {
          previousAdrMarkdown: feature?.adrMarkdown ?? "",
          grillTranscriptSummary: summarizeGrillTranscript(transcript),
          kickbackReason: formatActionItemReason(event.actionItems ?? []),
          requestedActionItems: event.actionItems ?? [],
          designSnapshots,
        },
      });
      return;
    }
    if (event.type === "submit_review") {
      // ADR 015 item 14-16: the internal Agentic Review verdict — never a
      // real GitHub PR review. `approved` -> in_review (Manual Review);
      // `changes_requested` -> returned with reason `agentic_review`.
      if (event.verdict === "approved") {
        await deps.features.approveReview(job.featureId);
      } else {
        await deps.features.setReturned(
          job.featureId,
          "agentic_review",
          event.summary ?? "Agentic Review requested changes",
        );
      }
      return;
    }
    await deps.features.setAwaitingUserInput(job.featureId, event.type === "ask_user");
    if (event.type === "run_failed") {
      await deps.features.updateStatus(job.featureId, "failed");
    } else if (event.type === "run_cancelled") {
      await deps.features.updateStatus(job.featureId, "cancelled");
    }
  } catch (error) {
    console.error(`failed to sync feature state for job ${jobId}:`, error);
  }
}


function formatActionItemReason(
  items: Array<{ type: string; description: string }>,
): string {
  if (items.length === 0) {
    return "Implementation reported that it is blocked and needs the specification revisited.";
  }
  return items
    .map((item) => `${item.type}: ${item.description}`)
    .join("\n");
}

/**
 * ADR 023: which model config tier and provider served a job, resolved from
 * the API's own catalog rather than reported by the Orchestrator — the
 * Orchestrator never learns provider names, and never handles a key on this
 * path (resolveModelConfigSource decrypts nothing).
 *
 * The provider is only knowable for the three catalog tiers: the two custom
 * tiers point at a bring-your-own endpoint that no catalog row describes, so
 * those are recorded with a null provider rather than a guessed one, and a
 * provider's own quota/billing-cycle reset is unknowable to Yggdrasil in every
 * case.
 *
 * Best-effort: an attribution lookup that fails still stores the job's real
 * token counts. Losing the tier label is a smaller loss than losing the
 * measurement.
 */
async function resolveUsageAttribution(
  deps: {
    projects: ProjectRepository;
    modelConfig: ModelConfigResolutionDeps;
  },
  job: { projectId: string; kind: JobKind; featureId: string | null },
): Promise<{ source: ModelConfigSource | null; providerName: string | null }> {
  if (!isAgentJobKind(job.kind)) {
    return { source: null, providerName: null };
  }
  try {
    const project = await deps.projects.findById(job.projectId);
    if (!project) {
      return { source: null, providerName: null };
    }
    const { source, modelId } = await resolveModelConfigSource(deps.modelConfig, {
      projectId: job.projectId,
      organizationId: project.organizationId,
      jobKind: job.kind,
      featureId: job.featureId,
    });
    const model = modelId
      ? await deps.modelConfig.models.findById(project.organizationId, modelId)
      : null;
    return { source, providerName: model?.providerName ?? null };
  } catch (error) {
    console.error(`failed to resolve usage attribution for project ${job.projectId}:`, error);
    return { source: null, providerName: null };
  }
}

/**
 * Narrows a stored job kind to the five agent-driven kinds ADR 018 resolves a
 * model config for. `deploy` and `script_test_run` run no Pi session, so they
 * never report usage at all; this guard means a report arriving for one (a
 * bug, or a future non-agent kind that does consume tokens) records its counts
 * with no tier attributed rather than a misleading one.
 */
function isAgentJobKind(kind: JobKind): kind is AgentJobKind {
  return (AGENT_JOB_KINDS as readonly string[]).includes(kind);
}
