import { Router } from "express";
import { z } from "zod";
import { requireInternalApiToken } from "../secrets/internal-auth.js";
import { routeParam } from "../shared/route-param.js";
import { isUuid } from "../shared/uuid.js";
import type { FeatureActionItemRepository } from "../features/action-items-repository.js";
import type { FeatureRepository } from "../features/repository.js";
import type { JobEventRepository } from "./events-repository.js";
import type { JobRepository } from "./repository.js";
import type { ProjectRepository } from "../projects/repository.js";
import type { TestRepository } from "../tests/repository.js";
import type { TestRunReportRepository } from "../tests/reports-repository.js";

const actionItemSchema = z.object({
  type: z.enum(["secret_request", "design_grill", "subtask_feature", "test_request"]),
  description: z.string(),
  secretKey: z.string().optional(),
  draftTestMarkdown: z.string().optional(),
});

const designSnapshotSchema = z
  .record(z.string().trim().min(1).max(256), z.string().max(500_000))
  .superRefine((snapshot, ctx) => {
    if (Object.keys(snapshot).length === 0) {
      ctx.addIssue({ code: "custom", message: "Design snapshots cannot be empty" });
    }
    if (Object.keys(snapshot).length > 100) {
      ctx.addIssue({ code: "custom", message: "Design snapshots may contain at most 100 files" });
    }
    for (const path of Object.keys(snapshot)) {
      if (
        path.startsWith("/") ||
        path.includes("\\") ||
        path.split("/").some((part) => part === ".." || part === ".")
      ) {
        ctx.addIssue({ code: "custom", message: "Design snapshot paths must be safe relative paths" });
        break;
      }
    }
  });

const jobEventSchema = z.object({
  type: z.enum([
    "agent_text",
    "ask_user",
    "submit_adr",
    "run_failed",
    "run_cancelled",
    "submit_build_result",
    "run_started",
    "request_action_item",
    "submit_review",
    "report_test_step",
    "submit_test_report",
    "update_design_preview",
    "submit_design",
  ]),
  question: z.string().optional(),
  markdown: z.string().optional(),
  message: z.string().optional(),
  status: z.string().optional(),
  prUrl: z.string().optional(),
  summary: z.string().optional(),
  // submit_review (ADR 015 item 14-16): the internal Agentic Review verdict.
  verdict: z.enum(["approved", "changes_requested"]).optional(),
  // ADR 015 item 4: submit_adr carries the Action Items batch generated by
  // this spec_grill run (optional).
  actionItems: z.array(actionItemSchema).optional(),
  testName: z.string().optional(),
  testStatus: z.enum(["pass", "fail"]).optional(),
  testDetails: z.string().optional(),
  screenshotPath: z.string().optional(),
  passed: z.number().int().nonnegative().optional(),
  failed: z.number().int().nonnegative().optional(),
  skipped: z.number().int().nonnegative().optional(),
  total: z.number().int().nonnegative().optional(),
  coveragePercent: z.number().min(0).max(100).optional(),
  failingTests: z.array(z.string()).optional(),
  recordingPath: z.string().optional(),
  snapshot: designSnapshotSchema.optional(),
  hasDesignSurface: z.boolean().optional(),
}).superRefine((event, ctx) => {
  if (event.type === "report_test_step" && (!event.testName || !event.testStatus)) {
    ctx.addIssue({
      code: "custom",
      message: "Test step reports require testName and testStatus",
    });
  }
  if (
    event.type === "submit_test_report" &&
    (event.passed === undefined || event.failed === undefined || !event.summary)
  ) {
    ctx.addIssue({
      code: "custom",
      message: "Test reports require passed, failed, and summary",
    });
  }
  if (
    event.type === "submit_test_report" &&
    event.total !== undefined &&
    event.passed !== undefined &&
    event.failed !== undefined &&
    event.total < event.passed + event.failed + (event.skipped ?? 0)
  ) {
    ctx.addIssue({
      code: "custom",
      message: "Test report total cannot be less than its result counts",
    });
  }
  if (
    (event.type === "update_design_preview" || event.type === "submit_design") &&
    !event.snapshot
  ) {
    ctx.addIssue({
      code: "custom",
      message: "Design events require a full path-to-content snapshot",
    });
  }
});

const requestedActionItemSchema = z.object({
  type: z.string(),
  description: z.string(),
});

/**
 * Accepts curated events the Orchestrator relays from a running job's Pi
 * RPC session (ADR 006 items 7-8) and persists them — the only place job
 * events enter the API. Read-side (WebSocket relay to the Web app,
 * notifications) is a tracked follow-up.
 */
export function createJobsInternalRouter(deps: {
  jobEvents: JobEventRepository;
  jobs: JobRepository;
  features: FeatureRepository;
  actionItems: FeatureActionItemRepository;
  tests: TestRepository;
  testRunReports: TestRunReportRepository;
  projects: ProjectRepository;
}): Router {
  const router = Router();

  router.post(
    "/jobs/:jobId/events",
    requireInternalApiToken,
    async (req, res) => {
      const jobId = routeParam(req.params.jobId);
      if (!isUuid(jobId)) {
        res.status(404).json({ error: "Job not found" });
        return;
      }

      const parsed = jobEventSchema.safeParse(req.body);
      if (!parsed.success) {
        res.status(400).json({ error: parsed.error.issues[0]?.message ?? "Invalid event" });
        return;
      }
      if (parsed.data.type === "update_design_preview" || parsed.data.type === "submit_design") {
        const job = await deps.jobs.findById(jobId);
        if (job?.kind !== "design_grill") {
          res.status(400).json({ error: "Design events require a design_grill job" });
          return;
        }
        const prefix = job.designSlug ? `designs/${job.designSlug}/` : null;
        if (prefix && parsed.data.snapshot && Object.keys(parsed.data.snapshot).some((path) => !path.startsWith(prefix))) {
          res.status(400).json({ error: "Design snapshot contains a path outside its design folder" });
          return;
        }
      }

      let event;
      try {
        event = await deps.jobEvents.create({
          jobId,
          ...parsed.data,
          message:
            parsed.data.type === "report_test_step"
              ? `${parsed.data.testName ?? "Test step"}: ${parsed.data.testStatus ?? "unknown"}`
              : parsed.data.message,
          summary:
            parsed.data.type === "submit_test_report"
              ? parsed.data.summary ?? ""
              : parsed.data.summary,
          snapshot: parsed.data.snapshot,
        });
      } catch (error) {
        console.error(`failed to record event for job ${jobId}:`, error);
        res.status(500).json({ error: "Failed to record job event" });
        return;
      }

      await syncFeatureState(deps, jobId, parsed.data);
      res.status(201).json({ id: event.id });
    },
  );

  return router;
}

/**
 * Reacts to the event just persisted by updating the feature it belongs to
 * (ADR 006 items 10-11; ADR 010 item 9): `ask_user` sets
 * `awaiting_user_input`, so the API/Web app can tell a grill is paused on a
 * human. `submit_adr` is spec_grill's successful terminal event: it stores
 * the submitted markdown and moves the feature `draft` -> `spec_ready`
 * (`FeatureRepository.setSpecReady`, which also clears
 * `awaiting_user_input` itself). `submit_build_result` is feature_build's
 * single terminal event, carrying its own outcome in `status`: `"success"`
 * moves the feature to `testing`, persists the opened PR's URL, and dispatches
 * one agentic `test_run` per enabled test
 * (`FeatureRepository.setTesting`); `"failure"` is handled exactly like
 * `run_failed` below. `run_failed`/`run_cancelled` are the run's
 * unsuccessful terminal events: each clears `awaiting_user_input` (so a job
 * that stops — dies, or is deliberately cancelled, ADR 006 item 13 — while
 * still waiting on a reply doesn't leave the flag stuck true forever) and
 * moves the feature to `failed`/`cancelled` respectively (ADR 007 item 8's
 * retry-grill route depends on a `project_init` feature actually reaching
 * `failed`, not staying on `draft` forever) — without this, the Web app has
 * no way to tell a grill died. feature_build never sets
 * `awaiting_user_input` true in the first place (its implement skill has no
 * ask_user tool, ADR 010), so `submit_build_result` doesn't touch it either
 * way, unlike run_failed/run_cancelled which unconditionally clear it.
 * `run_started` (ADR 011) is synthesized by the Orchestrator the moment a
 * job's pod is up, for both job kinds uniformly - `setRunning`'s own
 * `WHERE status = 'queued'` guard is what makes it a no-op for spec_grill
 * (whose feature sits in `draft`, not `queued`) without any job-kind check
 * here.
 *
 * Best-effort: a failure here doesn't undo the 201 already sent for the
 * event itself, since the event was persisted successfully regardless.
 */
async function syncFeatureState(
  deps: {
    jobs: JobRepository;
    features: FeatureRepository;
    actionItems: FeatureActionItemRepository;
    tests: TestRepository;
    testRunReports: TestRunReportRepository;
    projects: ProjectRepository;
  },
  jobId: string,
  event: z.infer<typeof jobEventSchema>,
): Promise<void> {
  if (
    event.type !== "ask_user" &&
    event.type !== "run_failed" &&
    event.type !== "run_cancelled" &&
    event.type !== "submit_adr" &&
    event.type !== "submit_build_result" &&
    event.type !== "run_started" &&
    event.type !== "request_action_item" &&
    event.type !== "submit_review" &&
    event.type !== "report_test_step" &&
    event.type !== "submit_test_report" &&
    event.type !== "update_design_preview" &&
    event.type !== "submit_design"
  ) {
    return;
  }
  try {
    const job = await deps.jobs.findById(jobId);
    if (
      (event.type === "update_design_preview" || event.type === "submit_design") &&
      job?.kind !== "design_grill"
    ) {
      return;
    }
    if (!job?.featureId) {
      return;
    }
    if (event.type === "run_started") {
      await deps.features.setRunning(job.featureId);
      return;
    }
    if (event.type === "submit_adr") {
      await deps.features.setSpecReady(job.featureId, event.markdown ?? "");
      if (event.hasDesignSurface !== undefined && deps.projects.setHasDesignSurface) {
        const feature = await deps.features.findById(job.projectId, job.featureId);
        if (feature?.featureType === "project_init") {
          await deps.projects.setHasDesignSurface(job.projectId, event.hasDesignSurface);
        }
      }
      // ADR 015 item 4: persist this spec_grill run's Action Items batch,
      // generated once at the draft -> spec_ready transition.
      if (event.actionItems && event.actionItems.length > 0) {
        await deps.actionItems.createMany(
          job.featureId,
          event.actionItems.map((item) => ({
            type: item.type,
            description: item.description,
            secretKey: item.secretKey,
            draftTestMarkdown: item.draftTestMarkdown,
          })),
        );
      }
      return;
    }
    if (event.type === "submit_build_result") {
      if (event.status === "success") {
        // ADR 015 item 3: Testing starts the instant a build succeeds; the
        // feature no longer jumps straight to in_review.
        const feature = await deps.features.findById(job.projectId, job.featureId);
        const updated = event.prUrl
          ? await deps.features.setTesting(job.featureId, event.prUrl)
          : await deps.features.setTesting(job.featureId);
        if (!updated || !feature) return;

        try {
          const enabledTests = await deps.tests.listEnabledByProject(job.projectId);
          if (enabledTests.length === 0) {
            await advanceAfterTesting(deps, job.projectId, job.featureId);
            return;
          }
          if (await deps.jobs.hasActiveFeatureTestRuns(job.featureId)) return;
          const ref = feature.branchName ?? `yggdrasil/${feature.slug}-${feature.id}`;
          for (const test of enabledTests) {
            await deps.jobs.create({
              projectId: job.projectId,
              kind: "test_run",
              featureId: job.featureId,
              testId: test.id,
              ref,
              trigger: "feature",
            });
          }
        } catch (error) {
          await deps.features.updateStatus(job.featureId, "failed");
          throw error;
        }
      } else {
        await deps.features.updateStatus(job.featureId, "failed");
      }
      return;
    }
    if (event.type === "report_test_step") {
      if (job.kind !== "test_run") return;
      if (!event.testName || !event.testStatus) return;
      await deps.testRunReports.upsertStep({
        jobId,
        name: event.testName,
        status: event.testStatus,
        details: event.testDetails,
        screenshotPath: event.screenshotPath,
      });
      return;
    }
    if (event.type === "submit_test_report") {
      if (job.kind !== "test_run") return;
      if (
        event.passed === undefined ||
        event.failed === undefined ||
        event.summary === undefined
      ) {
        return;
      }
      const skipped = event.skipped ?? 0;
      const total = event.total ?? event.passed + event.failed + skipped;
      await deps.testRunReports.upsertReport({
        jobId,
        passed: event.passed,
        failed: event.failed,
        skipped,
        total,
        coveragePercent: event.coveragePercent,
        failingTests: event.failingTests,
        summary: event.summary,
        recordingPath: event.recordingPath,
      });
      const runs = await deps.jobs.listFeatureTestRuns(job.featureId);
      const reports = await Promise.all(
        runs.map((run) => deps.testRunReports.findByJob(run.id)),
      );
      if (reports.some((report) => report === null)) return;
      if (reports.some((report) => report!.failed > 0)) {
        const failedReport = reports.find((report) => report!.failed > 0)!;
        await deps.features.setReturned(
          job.featureId,
          "test_failure",
          failedReport.summary,
        );
        return;
      }
      await advanceAfterTesting(deps, job.projectId, job.featureId);
      return;
    }
    if (event.type === "request_action_item") {
      // ADR 015 item 7-8: feature_build kicked back to Spec. Structurally
      // distinct from a crash (which stays `failed`, ADR 012): the `draft` ->
      // fresh spec_grill run is seeded with the prior context, and the old
      // Action Item batch is cleared so the new run's submit_adr regenerates
      // it cleanly.
      await deps.features.updateStatus(job.featureId, "draft");
      await deps.actionItems.clearForFeature(job.featureId);
      await deps.jobs.create({
        projectId: job.projectId,
        kind: "spec_grill",
        featureId: job.featureId,
      });
      return;
    }
    if (event.type === "submit_review") {
      // ADR 015 item 14-16: the internal Agentic Review verdict — never a
      // real GitHub PR review. `approved` -> in_review (Manual Review);
      // `changes_requested` -> returned with reason `agentic_review`.
      if (event.verdict === "approved") {
        await deps.features.approveReview(job.featureId);
      } else {
        await deps.features.setReturned(
          job.featureId,
          "agentic_review",
          event.summary ?? "Agentic Review requested changes",
        );
      }
      return;
    }
    await deps.features.setAwaitingUserInput(job.featureId, event.type === "ask_user");
    if (event.type === "run_failed") {
      await deps.features.updateStatus(job.featureId, "failed");
    } else if (event.type === "run_cancelled") {
      await deps.features.updateStatus(job.featureId, "cancelled");
    }
  } catch (error) {
    console.error(`failed to sync feature state for job ${jobId}:`, error);
  }
}

async function advanceAfterTesting(
  deps: {
    features: FeatureRepository;
    jobs: JobRepository;
    projects: ProjectRepository;
  },
  projectId: string,
  featureId: string,
): Promise<void> {
  const project = await deps.projects.findById(projectId);
  if (!project) return;
  if (!project.agenticReviewEnabled) {
    await deps.features.setInReview(featureId, "");
    return;
  }
  const advanced = await deps.features.setAgenticReview(featureId);
  if (!advanced) return;
  await deps.jobs.create({
    projectId,
    kind: "agentic_review",
    featureId,
  });
}
