import { Router } from "express";
import { z } from "zod";
import { requireInternalApiToken } from "../secrets/internal-auth.js";
import { routeParam } from "../shared/route-param.js";
import { isUuid } from "../shared/uuid.js";
import type { FeatureActionItemRepository } from "../features/action-items-repository.js";
import type { FeatureRepository } from "../features/repository.js";
import type { DesignRepository } from "../designs/repository.js";
import type { JobEventRepository } from "./events-repository.js";
import type { JobRepository } from "./repository.js";
import { GRILL_JOB_KINDS, type JobKind } from "./types.js";
import type { ProjectRepository } from "../projects/repository.js";
import type { TestRepository } from "../tests/repository.js";
import type { TestRunReportRepository } from "../tests/reports-repository.js";
import { AGENT_JOB_KINDS, type AgentJobKind, type ModelConfigSource } from "../model-config/types.js";
import {
  resolveModelConfigSource,
  type ModelConfigResolutionDeps,
} from "../secrets/model-config.js";
import type { JobUsageRepository } from "../usage/repository.js";
import { NOOP_LIVE_PUBLISHER, type LivePublisher } from "../live/deltas.js";
import { LIVE_DELTA_MAX_PAYLOAD_BYTES, deltaTextFitsPayload, liveScopeForJob } from "../live/types.js";
import { config } from "../config.js";
import { summarizeGrillTranscript } from "./grill-context.js";
import { UNKNOWN_CAPABILITIES, type JobKindCapabilities } from "./capabilities.js";
import { evaluateTestingGate } from "../features/testing-gate-runner.js";

const actionItemSchema = z.object({
  type: z.enum(["secret_request", "design_grill", "subtask_feature", "test_request"]),
  description: z.string(),
  secretKey: z.string().optional(),
  draftTestMarkdown: z.string().optional(),
});

const designSnapshotSchema = z
  .record(z.string().trim().min(1).max(256), z.string().max(500_000))
  .superRefine((snapshot, ctx) => {
    if (Object.keys(snapshot).length === 0) {
      ctx.addIssue({ code: "custom", message: "Design snapshots cannot be empty" });
    }
    if (Object.keys(snapshot).length > 100) {
      ctx.addIssue({ code: "custom", message: "Design snapshots may contain at most 100 files" });
    }
    for (const path of Object.keys(snapshot)) {
      if (
        path.startsWith("/") ||
        path.includes("\\") ||
        path.split("/").some((part) => part === ".." || part === ".")
      ) {
        ctx.addIssue({ code: "custom", message: "Design snapshot paths must be safe relative paths" });
        break;
      }
    }
  });

const jobEventSchema = z.object({
  type: z.enum([
    "agent_text",
    "ask_user",
    "submit_adr",
    "run_failed",
    "run_cancelled",
    "submit_build_result",
    "run_started",
    "request_action_item",
    "submit_review",
    "report_test_step",
    "submit_test_report",
    "update_design_preview",
    "submit_design",
    // Issue #27: synthesized by the Orchestrator, which reads the marker the
    // build pod's entrypoint wrote when it resolved conflicts with the base.
    "merge_conflicts",
    // ADR 032 item 3: the fork preamble stopped before the first turn.
    "fork_failed",
  ]),
  question: z.string().optional(),
  markdown: z.string().optional(),
  message: z.string().optional(),
  status: z.string().optional(),
  /**
   * ADR 032 item 3: which of the fork's three steps stopped, on a `fork_failed`
   * event. A closed enum mirroring the migration's CHECK, so an unrecognised stage
   * is refused at the boundary rather than stored as a value nothing can act on.
   *
   * Optional because no other event carries one, and its absence on a
   * `fork_failed` is answered by the handler rather than by a default — a default
   * would attribute a failure to a stage the Orchestrator never claimed.
   */
  forkStage: z.enum(["write", "switch", "fork"]).optional(),
  prUrl: z.string().optional(),
  summary: z.string().optional(),
  comment: z.string().optional(),
  // submit_review (ADR 015 item 14-16): the internal Agentic Review verdict.
  verdict: z.enum(["approved", "changes_requested"]).optional(),
  // ADR 015 item 4: submit_adr carries the Action Items batch generated by
  // this spec_grill run (optional).
  actionItems: z.array(actionItemSchema).optional(),
  testName: z.string().optional(),
  testStatus: z.enum(["pass", "fail"]).optional(),
  testDetails: z.string().optional(),
  screenshotPath: z.string().optional(),
  /**
   * Issue #38: the structured half of an `ask_user` question — a heading for the
   * control, whether more than one choice may be picked, and the choices.
   *
   * All three are optional on the object and their *relationship* is enforced in
   * the `superRefine` below, because "header is required when options are present"
   * is not expressible in a flat object schema without a discriminated union — and
   * a union here would make the error message a model receives harder to act on
   * than a sentence naming the missing field.
   *
   * The names match the tool's arguments exactly (`header`, `question`,
   * `multiSelect`, `options`), so a reader comparing
   * `extensions/yggdrasil-contract` with this schema is comparing the same words.
   */
  header: z.string().trim().min(1).max(128).optional(),
  multiSelect: z.boolean().optional(),
  options: z
    .array(
      z.object({
        label: z.string().trim().min(1).max(256),
        description: z.string().trim().max(512).optional(),
      }),
    )
    .max(20)
    .optional(),
  /**
   * Issue #73: a review's per-location findings, so the verdict's blockers are
   * countable and locatable instead of only prose in `comment`.
   *
   * **Optional, and its absence means "prose".** Every review written before this
   * existed carries none, and a reviewer may legitimately choose to write a
   * paragraph — the issue is explicit that the two modes coexist. So the schema
   * does not require it, and the storage distinguishes absent (`null`) from empty
   * (`[]`): only the latter is a statement that there are no findings.
   *
   * The names match the tool's arguments exactly (`path`, `line`, `body`,
   * `blocking`), so a reader comparing `agentic_review/skills/review/SKILL.md` and
   * `extensions/yggdrasil-contract` with this schema is comparing the same words —
   * the same rule `ask_user`'s structured half follows.
   *
   * Bounds mirror the sibling `options` list: a review with more than 50 findings
   * is a runaway, not a review, and an unbounded `body` would let one event row
   * carry a megabyte into every transcript read.
   */
  findings: z
    .array(
      z.object({
        path: z.string().trim().max(512).optional(),
        line: z.number().int().positive().optional(),
        body: z.string().trim().min(1).max(4000),
        blocking: z.boolean().optional(),
      }),
    )
    .max(50)
    .optional(),
  passed: z.number().int().nonnegative().optional(),
  failed: z.number().int().nonnegative().optional(),
  skipped: z.number().int().nonnegative().optional(),
  total: z.number().int().nonnegative().optional(),
  coveragePercent: z.number().min(0).max(100).optional(),
  failingTests: z.array(z.string()).optional(),
  recordingPath: z.string().optional(),
  /**
   * Issue #53: why a group did not run. A closed enum rather than a sentence in
   * `summary`, because the gate has to act on this and prose is not something to
   * branch on — see the migration's comment for the two failures that argument
   * rests on.
   *
   * Optional, and its absence means "the runner did not say": a producer that
   * does not send it changes no outcome, which is what lets the API land ahead
   * of the Orchestrator and the `script_test_run` entrypoint.
   */
  skipReason: z.enum(["no_script", "runner_unavailable"]).optional(),
  snapshot: designSnapshotSchema.optional(),
  hasDesignSurface: z.boolean().optional(),
}).superRefine((event, ctx) => {
  if (event.type === "report_test_step" && (!event.testName || !event.testStatus)) {
    ctx.addIssue({
      code: "custom",
      message: "Test step reports require testName and testStatus",
    });
  }
  /*
   * Issue #38: a structured question's halves only make sense together.
   *
   * `options` without `header` is the case worth a message: the contract the Web
   * app renders against expects a heading, and a model that supplied choices but
   * forgot the label is one correction away from a valid call. A bare `header`
   * with no `options` is harmless and therefore accepted rather than rejected —
   * it renders as a question with no control, which is the prose case.
   *
   * An empty `options` array is rejected rather than treated as prose: a tool
   * caller that *meant* to offer choices and produced none is a bug in the call,
   * and silently downgrading it to a text box would hide that from the model that
   * could fix it.
   */
  if (event.type === "ask_user") {
    if (event.options !== undefined) {
      if (!event.header) {
        ctx.addIssue({
          code: "custom",
          path: ["header"],
          message: "A question with options requires a header naming what is being chosen",
        });
      }
      if (event.options.length === 0) {
        ctx.addIssue({
          code: "custom",
          path: ["options"],
          message: "A question with options must offer at least one",
        });
      }
    }
    if (!event.question) {
      ctx.addIssue({
        code: "custom",
        path: ["question"],
        message: "An ask_user question requires the question text",
      });
    }
  }
  if (
    event.type === "submit_test_report" &&
    (event.passed === undefined || event.failed === undefined || !event.summary)
  ) {
    ctx.addIssue({
      code: "custom",
      message: "Test reports require passed, failed, and summary",
    });
  }
  if (
    event.type === "submit_test_report" &&
    event.total !== undefined &&
    event.passed !== undefined &&
    event.failed !== undefined &&
    event.total < event.passed + event.failed + (event.skipped ?? 0)
  ) {
    ctx.addIssue({
      code: "custom",
      message: "Test report total cannot be less than its result counts",
    });
  }
  if (
    (event.type === "update_design_preview" || event.type === "submit_design") &&
    !event.snapshot
  ) {
    ctx.addIssue({
      code: "custom",
      message: "Design events require a full path-to-content snapshot",
    });
  }
  if (event.type === "submit_review" && (!event.verdict || (!event.comment && !event.summary))) {
    ctx.addIssue({
      code: "custom",
      message: "Review events require a verdict and comment",
    });
  }
});

const requestedActionItemSchema = z.object({
  type: z.string(),
  description: z.string(),
});

/**
 * ADR 019 item 13: one streaming chunk of assistant text.
 *
 * Deliberately NOT a member of `jobEventSchema`'s enum, and deliberately its own
 * schema rather than a widened enum with a runtime exclusion. The stored-event
 * enum stays authoritative for what can become a `job_events` row, so
 * "`agent_text_delta` is relayed but never stored" is enforced by the shape of
 * the validation rather than by a branch someone could later reorder.
 *
 * **The bound is the publisher's own, measured the same way (issue #78).** The
 * original was `z.string().min(1).max(4_000)`, and `.max()` on a Zod string
 * counts **UTF-16 code units**, not bytes — while the comment above it justified
 * the number by a *byte* limit. The two could therefore only agree on ASCII, and
 * multi-byte text sat in the gap: 4000 CJK characters is 12000 bytes, which the
 * route accepted and `encodeDeltaPayload` then dropped. The producer was told
 * nothing (correctly — deltas are best-effort), so the only trace was a log line.
 *
 * So this does not bound the text at all — it asks `deltaTextFitsPayload`, which
 * runs the publisher's own `JSON.stringify` against the publisher's own ceiling.
 * One predicate, one answer.
 *
 * **Why not "text bytes ≤ ceiling minus a constant".** That was the first attempt
 * and it was wrong in the same direction as the bug: `JSON.stringify` *escapes*
 * characters, so 6891 newlines serialise to a 13891-byte payload rather than
 * 7000. A constant envelope left a gap twice as wide as the one being fixed. The
 * only honest measurement is the serialisation itself.
 *
 * `min(1)` stays: an empty delta carries no text and `encodeDeltaPayload` rejects
 * it, so accepting it here would just move the drop downstream.
 */
/**
 * Whether the body is *claiming* to be a streaming delta, regardless of whether
 * it validated.
 *
 * Used to route a failed delta parse to a delta-shaped error (issue #78). Kept
 * deliberately loose — `type` alone, no `message` check — because the point is to
 * recognise the *intent* of a malformed payload: a body with
 * `type: "agent_text_delta"` that fails validation is a bad delta, not a bad
 * stored event, and reporting it as the latter is what made the size bound's
 * message unreachable.
 */
function isDeltaBody(body: unknown): boolean {
  return (
    typeof body === "object" &&
    body !== null &&
    (body as { type?: unknown }).type === "agent_text_delta"
  );
}

const jobEventDeltaSchema = z.object({
  type: z.literal("agent_text_delta"),
  message: z
    .string()
    .min(1)
    .refine((text) => deltaTextFitsPayload(text), {
      message: `Delta text is too large to relay (over ${LIVE_DELTA_MAX_PAYLOAD_BYTES} bytes once serialised)`,
    }),
});

/**
 * ADR 023: the accounting block the Orchestrator reads from Pi's own
 * get_session_stats at the end of a job's session. Non-negative throughout —
 * Pi cannot legitimately report negative usage, so a negative value is a bug
 * upstream and is rejected rather than stored.
 */
const jobUsageSchema = z.object({
  modelId: z.string().trim().max(256).optional(),
  inputTokens: z.number().int().nonnegative(),
  outputTokens: z.number().int().nonnegative(),
  cacheReadTokens: z.number().int().nonnegative(),
  cacheWriteTokens: z.number().int().nonnegative(),
  totalTokens: z.number().int().nonnegative(),
  costUsd: z.number().nonnegative().nullable().optional(),
  durationMs: z.number().int().nonnegative().nullable().optional(),
});

/**
 * Accepts curated events the Orchestrator relays from a running job's Pi
 * RPC session (ADR 006 items 7-8) and persists them — the only place job
 * events enter the API. Read-side (WebSocket relay to the Web app,
 * notifications) is a tracked follow-up.
 */
export function createJobsInternalRouter(deps: {
  jobEvents: JobEventRepository;
  jobs: JobRepository;
  features: FeatureRepository;
  actionItems: FeatureActionItemRepository;
  tests: TestRepository;
  testRunReports: TestRunReportRepository;
  projects: ProjectRepository;
  designs: DesignRepository;
  usage: JobUsageRepository;
  modelConfig: ModelConfigResolutionDeps;
  /**
   * ADR 019 item 13's streaming-delta relay. Optional so the many tests that
   * build this router without caring about the live path keep working, and so a
   * deployment with the relay switched off can simply not pass one.
   */
  live?: LivePublisher;
  /**
   * Issue #24: total delta bytes relayed per job before its deltas stop being
   * relayed. Optional purely so a test can drive the boundary without a config
   * override; production takes `config.live.deltaBytesPerJob`.
   */
  deltaBytesPerJob?: number;
  /**
   * Issue #63: what the installation can actually run, so a probe kind with no
   * image is not dispatched. Optional and defaulting to the null object, so
   * every existing caller — and every install whose Orchestrator does not
   * publish capabilities — keeps dispatching exactly as before.
   */
  capabilities?: JobKindCapabilities;
}): Router {
  const router = Router();
  const live = deps.live ?? NOOP_LIVE_PUBLISHER;
  const deltaBytesPerJob = deps.deltaBytesPerJob ?? config.live.deltaBytesPerJob;

  /**
   * ADR 023: records a finished job's token/cost accounting.
   *
   * Scope is derived entirely from the stored job, never taken from the
   * request body: the caller is the Orchestrator reporting on a job it just
   * ran, so letting it name the project or the tier would make the usage table
   * assertable from outside rather than observed. The body carries only the
   * accounting itself.
   *
   * Not written to the audit trail: ADR 028 item 7 already scopes out
   * `/internal/*` Orchestrator-driven writes, each of which is a job outcome
   * the API itself just orchestrated rather than a human action.
   */
  router.post(
    "/jobs/:jobId/usage",
    requireInternalApiToken,
    async (req, res) => {
      const jobId = routeParam(req.params.jobId);
      if (!isUuid(jobId)) {
        res.status(404).json({ error: "Job not found" });
        return;
      }

      const parsed = jobUsageSchema.safeParse(req.body);
      if (!parsed.success) {
        res.status(400).json({ error: parsed.error.issues[0]?.message ?? "Invalid usage" });
        return;
      }

      const job = await deps.jobs.findById(jobId);
      if (!job) {
        res.status(404).json({ error: "Job not found" });
        return;
      }

      const attribution = await resolveUsageAttribution(deps, job);

      const usage = await deps.usage.upsert({
        jobId: job.id,
        projectId: job.projectId,
        jobKind: job.kind,
        modelId: parsed.data.modelId ?? null,
        modelConfigSource: attribution.source,
        providerName: attribution.providerName,
        inputTokens: parsed.data.inputTokens,
        outputTokens: parsed.data.outputTokens,
        cacheReadTokens: parsed.data.cacheReadTokens,
        cacheWriteTokens: parsed.data.cacheWriteTokens,
        totalTokens: parsed.data.totalTokens,
        costUsd: parsed.data.costUsd ?? null,
        durationMs: parsed.data.durationMs ?? null,
      });

      res.status(201).json({ id: usage.jobId });
    },
  );


  router.post(
    "/jobs/:jobId/events",
    requireInternalApiToken,
    async (req, res) => {
      const jobId = routeParam(req.params.jobId);
      if (!isUuid(jobId)) {
        res.status(404).json({ error: "Job not found" });
        return;
      }

      // ADR 019 item 13: streaming text deltas are relayed, never stored, so this
      // is checked BEFORE the stored-event schema — otherwise the enum would
      // reject the type and no delta would ever be relayed at all.
      //
      // The scope is derived from the stored job rather than taken from the
      // body, matching the usage route above: letting the caller name the
      // feature would make the routing of one feature's text to another
      // feature's subscribers assertable from outside.
      const delta = jobEventDeltaSchema.safeParse(req.body);
      if (delta.success) {
        await publishDelta(deps, live, jobId, delta.data.message, deltaBytesPerJob);
        // 202, not 201: nothing was created. For a delta that *fits*, the caller
        // still cannot tell a relayed one from a dropped one, and that is
        // intended — deltas are best-effort and an error would report something
        // the agent could not act on (the per-job ceiling can drop one
        // asynchronously, after this response).
        res.status(202).json({});
        return;
      }

      // Issue #78, caller-visible half: a delta that fails its *size* bound has to
      // say so. Without this it fell through to `jobEventSchema`, which rejects
      // the type — so an oversize payload was reported as an invalid event type,
      // and the schema's carefully-worded size message was unreachable. That was
      // also fragile in the other direction: adding `agent_text_delta` to the
      // stored-event enum, or reordering the two parses, would have turned an
      // oversize delta back into a silent 202-and-drop.
      if (isDeltaBody(req.body)) {
        res.status(400).json({
          error: delta.error.issues[0]?.message ?? "Invalid delta",
        });
        return;
      }

      const parsed = jobEventSchema.safeParse(req.body);
      if (!parsed.success) {
        res.status(400).json({ error: parsed.error.issues[0]?.message ?? "Invalid event" });
        return;
      }
      if (parsed.data.type === "update_design_preview" || parsed.data.type === "submit_design") {
        const job = await deps.jobs.findById(jobId);
        if (job?.kind !== "design_grill") {
          res.status(400).json({ error: "Design events require a design_grill job" });
          return;
        }
        const prefix = job.designSlug ? `designs/${job.designSlug}/` : null;
        if (prefix && parsed.data.snapshot && Object.keys(parsed.data.snapshot).some((path) => !path.startsWith(prefix))) {
          res.status(400).json({ error: "Design snapshot contains a path outside its design folder" });
          return;
        }
      }
      if (parsed.data.type === "submit_review") {
        const job = await deps.jobs.findById(jobId);
        if (job?.kind !== "agentic_review") {
          res.status(400).json({ error: "Review events require an agentic_review job" });
          return;
        }
      }
      /*
       * Issue #38's "where the tool lives" question, enforced rather than assumed.
       *
       * The *prevention* is the skills' `allowed-tools` frontmatter: `ask_user` is
       * listed by the three grill skills only, so a `feature_build` agent never has
       * the tool in its list. This is the backstop for the day that changes.
       *
       * Why a hard rejection rather than accepting the event: `ask_user` ends the
       * agent's *turn* without ending the run (it is deliberately absent from
       * `CuratedEvent.Terminal`), after which the Orchestrator blocks on
       * `WaitForReply`. On a job kind with no chat surface there is no reply to
       * wait for and no timeout — so accepting one here produces a run that hangs
       * indefinitely with nothing on screen to explain it. Failing the event post
       * instead turns a silent infinite stall into a logged error naming the job
       * and kind, which is the better of the two failures the issue asks us to
       * choose between.
       */
      if (parsed.data.type === "ask_user") {
        const job = await deps.jobs.findById(jobId);
        if (job && !GRILL_JOB_KINDS.has(job.kind)) {
          res.status(400).json({
            error: `ask_user requires a job kind with a chat surface; job ${jobId} is ${job.kind}`,
          });
          return;
        }
      }

      let event;
      try {
        event = await deps.jobEvents.create({
          jobId,
          ...parsed.data,
          message:
            parsed.data.type === "report_test_step"
              ? `${parsed.data.testName ?? "Test step"}: ${parsed.data.testStatus ?? "unknown"}`
              : parsed.data.message,
          summary:
            parsed.data.type === "submit_test_report"
              ? parsed.data.summary ?? ""
              : parsed.data.type === "submit_review"
                ? parsed.data.comment ?? parsed.data.summary
                : parsed.data.summary,
          // Issue #59: named explicitly rather than left to the spread above.
          // Relying on `...parsed.data` is how the verdict came to be validated,
          // acted on, and then dropped without a type error — a caller spreading
          // a wider object satisfies a narrower parameter, so an undeclared field
          // is discarded silently. Spelling it means removing it is a compile
          // error rather than a quiet loss.
          verdict: parsed.data.verdict,
          /*
           * Issue #38: spelled out for the reason the `verdict` comment above
           * gives. The tool's structured half arrives as three separate fields on
           * the request body, and the repository takes one object — so building
           * it here is not just tidiness, it is the only way `question_form` is
           * written at all. A spread of `parsed.data` into a narrower parameter
           * discards what the parameter does not declare, which is how the verdict
           * was validated, acted on, and then silently dropped (`#59`).
           *
           * `header ?? null` rather than `?? ""`: the schema requires a header
           * whenever options are present, so null here means "prose question",
           * and an empty string would render as a blank heading instead.
           */
          questionForm:
            parsed.data.type === "ask_user" && parsed.data.options
              ? {
                  header: parsed.data.header ?? null,
                  multiSelect: parsed.data.multiSelect ?? false,
                  options: parsed.data.options.map((option) => ({
                    label: option.label,
                    description: option.description ?? null,
                  })),
                }
              : null,
          actionItems: parsed.data.actionItems,
          snapshot: parsed.data.snapshot,
          /*
           * Issue #73: spelled out rather than left to the `...parsed.data` spread,
           * for the reason the `verdict` comment above gives at length — an
           * undeclared field is discarded silently, which is exactly how #59 lost
           * the verdict. The mapping is not cosmetic either: the request carries
           * optional fields (`path`/`line`/`blocking`) and the column's shape wants
           * them explicitly null/false rather than undefined, so a renderer never
           * has to distinguish "absent" from "false" for a field the producer
           * simply omitted.
           *
           * `findings === undefined` ⇒ null (prose, or pre-#73), and `[]` ⇒ `[]`
           * (structured with nothing found). The two are different answers to "how
           * many blocking issues", which is why this does not default to `[]`.
           */
          reviewFindings:
            parsed.data.type === "submit_review" && parsed.data.findings !== undefined
              ? parsed.data.findings.map((finding) => ({
                  path: finding.path ?? null,
                  line: finding.line ?? null,
                  body: finding.body,
                  // Defaults to **true**, matching the read contract's own default
                  // (`web/lib/features/agentic-review.ts`). The issue that specified
                  // this endpoint described the findings as *the blocking flags*, so
                  // an omitted flag means "these are the blockers", not "none of
                  // these matter" — and defaulting to false would let a review pass
                  // its gate while displaying the findings that should stop it.
                  blocking: finding.blocking ?? true,
                }))
              : null,
        });
      } catch (error) {
        console.error(`failed to record event for job ${jobId}:`, error);
        res.status(500).json({ error: "Failed to record job event" });
        return;
      }

      await syncFeatureState(deps, jobId, parsed.data);
      res.status(201).json({ id: event.id });
    },
  );

  return router;
}

/**
 * Relays one streaming delta to a feature's subscribers (ADR 019 item 13).
 *
 * Never throws and never fails the request: the delta is ephemeral, the client
 * already has a REST catch-up path, and the authoritative text still arrives as
 * `agent_text`. A failure here is logged so it is visible without being
 * propagated to a caller that has no way to act on it.
 *
 * A job with no `feature_id` (ADR 014's project-scoped `design_grill`) has no
 * feature topic to route to and is dropped, exactly as the stored-event relay
 * drops one.
 *
 * **Issue #24's per-job ceiling lives here**, and this is the only place it can:
 * it is the ingest for every delta, so it sees the whole of a job's stream
 * regardless of which replica served the POST.
 *
 * What reaching the ceiling does — and deliberately does not — do:
 *
 *  - It stops relaying that job's deltas. Nothing is lost by doing so. The
 *    authoritative `agent_text` for every message arrives over the stored-event
 *    path and is what the Web app renders a finished bubble from; deltas only
 *    make it appear sooner. So the ceiling costs immediacy, never content — the
 *    same trade-off `EventAgentTextDelta` documents.
 *  - It does **not** close subscribers' sockets, which is where it differs from
 *    the per-socket frame budget. A runaway is the *producer's* problem: the
 *    people watching the feature did nothing, and evicting them from live
 *    updates for a job they are not running would be punishing the wrong party.
 *  - It does **not** fail the job. The relay is an accelerator, not a control
 *    plane, and failing a build because its narration got long would be a
 *    spectacular overreach.
 *
 * The crossing is logged exactly once per job, using the `previousBytes` the
 * atomic update returns rather than an in-memory set of already-warned jobs
 * (which would grow without bound and would be per-replica, so it would log once
 * per replica anyway).
 */
async function publishDelta(
  deps: { jobs: JobRepository },
  live: LivePublisher,
  jobId: string,
  text: string,
  maxBytesPerJob: number = config.live.deltaBytesPerJob,
): Promise<void> {
  try {
    const recorded = await deps.jobs.recordRelayedDeltaBytes(
      jobId,
      Buffer.byteLength(text),
    );
    if (!recorded) return;

    // ADR 033 §5: the scope is resolved from the job rather than taken from the
    // body, and through the *same* function the stored-event path uses, so a
    // streaming chunk and the `agent_text` that supersedes it cannot be routed by
    // two different rules. Version 1 returned early on `!recorded.featureId`, which
    // is exactly why a design session's prose arrived per message instead of per
    // token (issue #95).
    //
    // **The *primary* scope, which is the deliberate half of issue #100.** A delta's
    // payload carries exactly one `scope` (ADR 033 §5), so this path must pick one —
    // and it picks the same one version 1 did: for a feature-driven `test_run` that
    // is `feature:`, where the feature's own surfaces are listening. The stored
    // event goes to *both* that job's scopes, because it is the record each surface
    // renders; a delta is progressive text, and the Test entity's run history shows
    // runs, steps and reports rather than agent prose, so a second copy of every
    // chunk would be published and consumed by nobody — the shape this burn-down
    // keeps finding. If a surface ever renders a run's live output, this is the line
    // to revisit, and `liveScopesForJob` is already the plural it would need.
    const scope = liveScopeForJob({
      jobId,
      featureId: recorded.featureId,
      jobKind: recorded.jobKind,
      testId: recorded.testId,
    });
    if (!scope) return;

    // `0` means the ceiling is switched off, matching the convention
    // `RECORDING_MAX_BYTES` already sets in this codebase: 0 is a meaningful
    // instruction (relay everything), not an unset value to be replaced by a
    // default. Checked before the comparison so a 0 can never be read as "no
    // bytes permitted".
    if (maxBytesPerJob > 0 && recorded.totalBytes > maxBytesPerJob) {
      if (recorded.previousBytes <= maxBytesPerJob) {
        console.error(
          `live relay: job ${jobId} exceeded the per-job delta ceiling ` +
            `(${recorded.totalBytes} bytes > ${maxBytesPerJob}); its deltas are no longer relayed. ` +
            `Nothing is lost — the authoritative agent_text still arrives over the stored-event path.`,
        );
      }
      return;
    }

    await live.publishDelta({ scope, jobId, text });
  } catch (error) {
    console.error(`failed to relay event delta for job ${jobId}:`, error);
  }
}

/**
 * Reacts to the event just persisted by updating the feature it belongs to
 * (ADR 006 items 10-11; ADR 010 item 9): `ask_user` sets
 * `awaiting_user_input`, so the API/Web app can tell a grill is paused on a
 * human. `submit_adr` is spec_grill's successful terminal event: it stores
 * the submitted markdown and moves the feature `draft` -> `spec_ready`
 * (`FeatureRepository.setSpecReady`, which also clears
 * `awaiting_user_input` itself). `submit_build_result` is feature_build's
 * single terminal event, carrying its own outcome in `status`: `"success"`
 * moves the feature to `testing`, persists the opened PR's URL, and dispatches
 * one agentic `test_run` per enabled test and one script job per
 * structure-standard test script
 * (`FeatureRepository.setTesting`); `"failure"` is handled exactly like
 * `run_failed` below. `run_failed`/`run_cancelled` are the run's
 * unsuccessful terminal events: each clears `awaiting_user_input` (so a job
 * that stops — dies, or is deliberately cancelled, ADR 006 item 13 — while
 * still waiting on a reply doesn't leave the flag stuck true forever) and
 * moves the feature to `failed`/`cancelled` respectively (ADR 007 item 8's
 * retry-grill route depends on a `project_init` feature actually reaching
 * `failed`, not staying on `draft` forever) — without this, the Web app has
 * no way to tell a grill died. feature_build never sets
 * `awaiting_user_input` true in the first place (its implement skill has no
 * ask_user tool, ADR 010), so `submit_build_result` doesn't touch it either
 * way, unlike run_failed/run_cancelled which unconditionally clear it.
 * `run_started` (ADR 011) is synthesized by the Orchestrator the moment a
 * job's pod is up, for both job kinds uniformly - `setRunning`'s own
 * `WHERE status = 'queued'` guard is what makes it a no-op for spec_grill
 * (whose feature sits in `draft`, not `queued`) without any job-kind check
 * here.
 *
 * Best-effort: a failure here doesn't undo the 201 already sent for the
 * event itself, since the event was persisted successfully regardless.
 */
async function syncFeatureState(
  deps: {
    jobEvents: JobEventRepository;
    jobs: JobRepository;
    features: FeatureRepository;
    actionItems: FeatureActionItemRepository;
    tests: TestRepository;
    testRunReports: TestRunReportRepository;
    projects: ProjectRepository;
    designs: DesignRepository;
    /** Issue #63: so a script probe the installation cannot run is not dispatched. */
    capabilities?: JobKindCapabilities;
  },
  jobId: string,
  event: z.infer<typeof jobEventSchema>,
): Promise<void> {
  if (
    event.type !== "ask_user" &&
    event.type !== "run_failed" &&
    event.type !== "run_cancelled" &&
    event.type !== "submit_adr" &&
    event.type !== "submit_build_result" &&
    event.type !== "run_started" &&
    event.type !== "request_action_item" &&
    event.type !== "submit_review" &&
    event.type !== "report_test_step" &&
    event.type !== "submit_test_report" &&
    event.type !== "update_design_preview" &&
    event.type !== "submit_design" &&
    // ADR 032 item 3. This list is the difference between an event being stored
    // and an event being *acted on*: `fork_failed` reaches the table either way,
    // because the route persists before it syncs, so without this arm the failure
    // is recorded and the feature stays whatever it was — the "declared,
    // marshalled and discarded" shape this burn-down has found seven times, in its
    // most literal form.
    event.type !== "fork_failed"
  ) {
    return;
  }
  try {
    const job = await deps.jobs.findById(jobId);
    if (
      (event.type === "update_design_preview" || event.type === "submit_design") &&
      job?.kind !== "design_grill"
    ) {
      return;
    }
    if (event.type === "submit_design") {
      // ADR 020 item 4: this is the moment the design becomes committed and
      // worth browsing — `submit_design` is the skill's own finalize step,
      // which has already committed `designs/<slug>/` and opened the draft PR.
      // Keyed by (project_id, slug) and upserted, so it also repairs a design
      // whose index row was never written.
      if (job && job.designSlug && job.designName) {
        try {
          await deps.designs.finalize({
            projectId: job.projectId,
            name: job.designName,
            slug: job.designSlug,
            jobId: job.id,
            prUrl: event.prUrl ?? null,
          });
        } catch (error) {
          console.error(`failed to finalize design for job ${jobId}:`, error);
        }
      }
      if (event.snapshot && deps.actionItems.resolveDesignSession) {
        await deps.actionItems.resolveDesignSession(jobId, event.snapshot);
      }
      return;
    }
    if (event.type === "update_design_preview" || !job?.featureId) {
      return;
    }
    if (event.type === "run_started") {
      await deps.features.setRunning(job.featureId);
      return;
    }
    if (event.type === "submit_adr") {
      await deps.features.setSpecReady(job.featureId, event.markdown ?? "");
      if (event.hasDesignSurface !== undefined && deps.projects.setHasDesignSurface) {
        const feature = await deps.features.findById(job.projectId, job.featureId);
        if (feature?.featureType === "project_init") {
          await deps.projects.setHasDesignSurface(job.projectId, event.hasDesignSurface);
        }
      }
      // ADR 015 item 4: persist this spec_grill run's Action Items batch,
      // generated once at the draft -> spec_ready transition.
      if (event.actionItems && event.actionItems.length > 0) {
        const actionItems = [];
        for (const item of event.actionItems) {
          let subtaskFeatureId: string | null = null;
          if (item.type === "subtask_feature" && deps.features.createSubtask) {
            const subtask = await deps.features.createSubtask({
              projectId: job.projectId,
              parentFeatureId: job.featureId,
              title: item.description,
            });
            await deps.jobs.create({
              projectId: job.projectId,
              kind: "spec_grill",
              featureId: subtask.id,
            });
            subtaskFeatureId = subtask.id;
          }
          actionItems.push({
            type: item.type,
            description: item.description,
            secretKey: item.secretKey,
            draftTestMarkdown: item.draftTestMarkdown,
            subtaskFeatureId,
          });
        }
        await deps.actionItems.createMany(
          job.featureId,
          actionItems,
        );
      }
      return;
    }
    if (event.type === "submit_build_result") {
      if (event.status === "success") {
        // ADR 015 item 3: Testing starts the instant a build succeeds; the
        // feature no longer jumps straight to in_review.
        const feature = await deps.features.findById(job.projectId, job.featureId);
        const updated = event.prUrl
          ? await deps.features.setTesting(job.featureId, event.prUrl)
          : await deps.features.setTesting(job.featureId);
        if (!updated || !feature) return;

        try {
          const enabledTests = await deps.tests.listEnabledByProject(job.projectId);
          if (await deps.jobs.hasActiveFeatureTestRuns(job.featureId)) return;
          const ref = feature.branchName ?? `yggdrasil/${feature.slug}-${feature.id}`;
          for (const test of enabledTests) {
            await deps.jobs.create({
              projectId: job.projectId,
              kind: "test_run",
              featureId: job.featureId,
              testId: test.id,
              ref,
              trigger: "feature",
            });
          }
          // The presence of test-unit.sh/test-integration.sh in the checked
          // out feature branch is the group's toggle (ADR 015 item 10).
          // Dispatch both probes here; the runner reports a missing script as
          // an empty, skipped group, so the API never needs to parse a repo or
          // maintain a second project-level setting.
          //
          // Issue #63: unless the installation cannot run the kind at all. An
          // install with no `script_test_run` image cannot execute either probe,
          // so dispatching them creates two job rows that can only fail — and,
          // since #53, that failure is what marks a feature `failed` at Testing
          // for a reason which is a *setting*, not a defect in the code. The
          // read defaults to "runnable" when the Orchestrator has not reported,
          // which keeps this behaviour-identical on every install until it does.
          const unrunnable = await readUnrunnableKinds(deps.capabilities, job.projectId);
          if (!unrunnable.has("script_test_run")) {
            for (const testGroup of ["unit", "integration"] as const) {
              await deps.jobs.create({
                projectId: job.projectId,
                kind: "script_test_run",
                featureId: job.featureId,
                testGroup,
                ref,
                trigger: "feature",
              });
            }
          }
        } catch (error) {
          await deps.features.updateStatus(job.featureId, "failed");
          throw error;
        }
      } else {
        await deps.features.updateStatus(job.featureId, "failed");
      }
      return;
    }
    if (event.type === "report_test_step") {
      if (job.kind !== "test_run") return;
      if (!event.testName || !event.testStatus) return;
      await deps.testRunReports.upsertStep({
        jobId,
        name: event.testName,
        status: event.testStatus,
        details: event.testDetails,
        screenshotPath: event.screenshotPath,
      });
      return;
    }
    if (event.type === "submit_test_report") {
      if (job.kind !== "test_run" && job.kind !== "script_test_run") return;
      if (
        event.passed === undefined ||
        event.failed === undefined ||
        event.summary === undefined
      ) {
        return;
      }
      const skipped = event.skipped ?? 0;
      const total = event.total ?? event.passed + event.failed + skipped;
      await deps.testRunReports.upsertReport({
        jobId,
        passed: event.passed,
        failed: event.failed,
        skipped,
        total,
        coveragePercent: event.coveragePercent,
        failingTests: event.failingTests,
        summary: event.summary,
        recordingPath: event.recordingPath,
        skipReason: event.skipReason,
      });
      // Issue #40: the gate decides whether the *runs* are done, not whether
      // every one of them submitted a report. The old check bailed while any run
      // lacked one, so a run that never reported (a container that never started)
      // blocked the feature in `testing` forever.
      await evaluateTestingGate(deps, job.projectId, job.featureId);
      return;
    }
    if (event.type === "request_action_item") {
      // ADR 015 item 7-8: feature_build kicked back to Spec. Structurally
      // distinct from a crash (which stays `failed`, ADR 012): the `draft` ->
      // fresh spec_grill run is seeded with the prior context, and the old
      // Action Item batch is cleared so the new run's submit_adr regenerates
      // it cleanly.
      const feature = await deps.features.findById(job.projectId, job.featureId);
      const transcript =
        (await deps.jobEvents.listSpecGrillByFeature?.(job.featureId)) ?? [];
      const designSnapshots =
        (await deps.actionItems.listResolvedDesignSnapshots?.(job.featureId)) ?? [];
      await deps.features.updateStatus(job.featureId, "draft");
      await deps.actionItems.clearForFeature(job.featureId);
      await deps.jobs.create({
        projectId: job.projectId,
        kind: "spec_grill",
        featureId: job.featureId,
        specContext: {
          previousAdrMarkdown: feature?.adrMarkdown ?? "",
          grillTranscriptSummary: summarizeGrillTranscript(transcript),
          kickbackReason: formatActionItemReason(event.actionItems ?? []),
          requestedActionItems: event.actionItems ?? [],
          designSnapshots,
        },
      });
      return;
    }
    if (event.type === "fork_failed") {
      // ADR 032 item 3: a fork that could not start is a failed run, and the
      // *reason* is the stage the Orchestrator named rather than a generic error —
      // "the artifact never arrived", "it arrived and Pi loaded nothing" and "the
      // resume point was rejected" ask three different things of the operator.
      //
      // Set here rather than produced by the frontend, because a surface that
      // derived its own wording would be a second reading of the same fact — the
      // shape this burn-down keeps finding (a value recorded in one place and
      // restated in another, free to disagree).
      // The stage itself rides on the stored event (`fork_stage`), which is what a
      // surface reads to say *which* step stopped. Nothing is copied onto the
      // feature row: a second copy of a fact recorded in one place is free to
      // disagree with it, and the event is the record.
      await deps.features.updateStatus(job.featureId, "failed");
      return;
    }
    if (event.type === "submit_review") {
      // ADR 015 item 14-16: the internal Agentic Review verdict — never a
      // real GitHub PR review. `approved` -> in_review (Manual Review);
      // `changes_requested` -> returned with reason `agentic_review`.
      if (event.verdict === "approved") {
        await deps.features.approveReview(job.featureId);
      } else {
        await deps.features.setReturned(
          job.featureId,
          "agentic_review",
          event.summary ?? "Agentic Review requested changes",
        );
      }
      return;
    }
    await deps.features.setAwaitingUserInput(job.featureId, event.type === "ask_user");
    if (event.type === "run_failed") {
      await deps.features.updateStatus(job.featureId, "failed");
    } else if (event.type === "run_cancelled") {
      await deps.features.updateStatus(job.featureId, "cancelled");
    }
  } catch (error) {
    console.error(`failed to sync feature state for job ${jobId}:`, error);
  }
}


function formatActionItemReason(
  items: Array<{ type: string; description: string }>,
): string {
  if (items.length === 0) {
    return "Implementation reported that it is blocked and needs the specification revisited.";
  }
  return items
    .map((item) => `${item.type}: ${item.description}`)
    .join("\n");
}

/**
 * ADR 023: which model config tier and provider served a job, resolved from
 * the API's own catalog rather than reported by the Orchestrator — the
 * Orchestrator never learns provider names, and never handles a key on this
 * path (resolveModelConfigSource decrypts nothing).
 *
 * The provider is only knowable for the three catalog tiers: the two custom
 * tiers point at a bring-your-own endpoint that no catalog row describes, so
 * those are recorded with a null provider rather than a guessed one, and a
 * provider's own quota/billing-cycle reset is unknowable to Yggdrasil in every
 * case.
 *
 * Best-effort: an attribution lookup that fails still stores the job's real
 * token counts. Losing the tier label is a smaller loss than losing the
 * measurement.
 */
async function resolveUsageAttribution(
  deps: {
    projects: ProjectRepository;
    modelConfig: ModelConfigResolutionDeps;
  },
  job: { projectId: string; kind: JobKind; featureId: string | null },
): Promise<{ source: ModelConfigSource | null; providerName: string | null }> {
  if (!isAgentJobKind(job.kind)) {
    return { source: null, providerName: null };
  }
  try {
    const project = await deps.projects.findById(job.projectId);
    if (!project) {
      return { source: null, providerName: null };
    }
    const { source, modelId } = await resolveModelConfigSource(deps.modelConfig, {
      projectId: job.projectId,
      organizationId: project.organizationId,
      jobKind: job.kind,
      featureId: job.featureId,
    });
    const model = modelId
      ? await deps.modelConfig.models.findById(project.organizationId, modelId)
      : null;
    return { source, providerName: model?.providerName ?? null };
  } catch (error) {
    console.error(`failed to resolve usage attribution for project ${job.projectId}:`, error);
    return { source: null, providerName: null };
  }
}

/**
 * Narrows a stored job kind to the five agent-driven kinds ADR 018 resolves a
 * model config for. `deploy` and `script_test_run` run no Pi session, so they
 * never report usage at all; this guard means a report arriving for one (a
 * bug, or a future non-agent kind that does consume tokens) records its counts
 * with no tier attributed rather than a misleading one.
 */
function isAgentJobKind(kind: JobKind): kind is AgentJobKind {
  return (AGENT_JOB_KINDS as readonly string[]).includes(kind);
}

/**
 * Issue #63: the job kinds this installation has reported it cannot run.
 *
 * A failed read answers "nothing is known to be unrunnable" rather than
 * propagating, for the same reason the gate's own capability read does: this runs
 * inside a job-event handler, and a thrown error here would fail the *build* — a
 * feature that built successfully marked failed because a capability lookup had a
 * bad moment. Dispatching a probe that turns out to be skippable is the
 * recoverable direction (it is reported, and #53 made the gate fail on it);
 * failing a good build is not.
 */
async function readUnrunnableKinds(
  configured: JobKindCapabilities | undefined,
  projectId: string,
): Promise<ReadonlySet<string>> {
  const capabilities = configured ?? UNKNOWN_CAPABILITIES;
  try {
    return await capabilities.unrunnable();
  } catch (error) {
    console.error(
      `failed to read installation capabilities for project ${projectId}; ` +
        `dispatching test probes as if every kind were runnable:`,
      error,
    );
    return new Set<string>();
  }
}
