import crypto from "node:crypto";
import { afterAll, describe, expect, it } from "vitest";
import {
  ObjectStorageError,
  S3ObjectStorage,
  createObjectStorage,
  type ObjectStorage,
} from "./client.js";
import { encodePathSegments, signRequest, uriEncode } from "./signature.js";

/**
 * Issue #30's verification, in two halves that answer different questions.
 *
 * **The contract tests at the bottom run against a real MinIO.** That is
 * deliberate and is the point: this repository's tests otherwise use fakes, and
 * a fake S3 client would verify nothing about the thing that actually breaks —
 * whether the signature the server computes matches the one we sent. Issue #43
 * (a repository method that always threw `42P08`) hid behind 880 green tests for
 * exactly that reason, so a hand-rolled signer verified only against a mock of
 * itself would be the same mistake with a different accent. The suite's
 * `docker-compose.test.yml` already runs MinIO and passes `S3_*` to this
 * container; these tests use it.
 *
 * **The signing tests above them are structural.** They pin the properties that
 * are easy to get subtly wrong (header ordering, RFC 3986 encoding, scope
 * derivation) rather than a golden signature, because a golden signature
 * generated by this implementation would only assert that it still produces what
 * it produced yesterday. Correctness against the actual server is the contract
 * tests' job.
 */

describe("uriEncode", () => {
  it("escapes the characters encodeURIComponent leaves alone", () => {
    // SigV4 requires RFC 3986; `encodeURIComponent` is close but leaves these
    // five, and an S3 key may legally contain all of them. A key that differed
    // in one of them would sign fine and then fail with SignatureDoesNotMatch.
    expect(uriEncode("!'()*")).toBe("%21%27%28%29%2A");
  });

  it("leaves unreserved characters as they are", () => {
    expect(uriEncode("aZ0-_.~")).toBe("aZ0-_.~");
  });

  it("encodes a space as %20 rather than +", () => {
    // `+` means a literal plus in a URI path, so an unencoded space would
    // address a different object.
    expect(uriEncode("a b")).toBe("a%20b");
  });
});

describe("encodePathSegments", () => {
  it("keeps separators and encodes the segments between them", () => {
    expect(encodePathSegments("/bucket/a b/c")).toBe("/bucket/a%20b/c");
  });

  it("does not collapse or reorder empty segments", () => {
    // `a//b` and `a/b` are different keys; normalising here would silently
    // address the wrong object.
    expect(encodePathSegments("/bucket/a//b")).toBe("/bucket/a//b");
  });
});

describe("signRequest", () => {
  const credentials = { accessKeyId: "AKIDEXAMPLE", secretAccessKey: "not-a-real-key" };
  const now = new Date("2026-09-18T12:34:56.000Z");

  function sign(overrides: Partial<Parameters<typeof signRequest>[1]> = {}) {
    return signRequest(credentials, {
      method: "PUT",
      canonicalUri: "/bucket/key",
      canonicalQuery: "",
      host: "minio:9000",
      region: "us-east-1",
      payload: Buffer.from("hello"),
      now,
      ...overrides,
    });
  }

  it("is deterministic for fixed inputs", () => {
    expect(sign().headers.Authorization).toBe(sign().headers.Authorization);
  });

  it("names the credential, scope and signed headers in the header", () => {
    const { headers } = sign();

    expect(headers.Authorization).toMatch(
      /^AWS4-HMAC-SHA256 Credential=AKIDEXAMPLE\/20260918\/us-east-1\/s3\/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=[0-9a-f]{64}$/,
    );
  });

  it("sorts signed header names, because that is what the canonical form is over", () => {
    const { headers, canonicalRequest } = sign({
      // Deliberately not supplied in sorted order.
      extraHeaders: { "x-amz-meta-b": "2", "content-type": "text/plain" },
    });

    expect(headers.Authorization).toContain(
      "SignedHeaders=content-type;host;x-amz-content-sha256;x-amz-date;x-amz-meta-b",
    );
    // And the canonical request's header block is in the same order, lowercased.
    expect(canonicalRequest).toContain(
      "content-type:text/plain\nhost:minio:9000\n",
    );
  });

  it("lowercases the host it signs", () => {
    // The header on the wire is what the server sees; a mixed-case Host that was
    // signed as given would mismatch on any client that normalised it.
    expect(sign({ host: "minio:9000" }).canonicalRequest).toContain("host:minio:9000");
  });

  it("changes the signature when the region changes", () => {
    // The scope is part of the signing key, so a region mismatch is a signature
    // mismatch rather than something the server can helpfully report.
    expect(sign({ region: "eu-west-1" }).headers.Authorization).not.toBe(
      sign().headers.Authorization,
    );
  });

  it("changes the signature when the payload changes", () => {
    // The payload hash is both a signed header and the last line of the
    // canonical request, which is what binds the body to the signature.
    expect(sign({ payload: Buffer.from("hello!") }).headers.Authorization).not.toBe(
      sign().headers.Authorization,
    );
  });

  it("hashes an empty payload to the well-known SHA-256 of nothing", () => {
    const empty = crypto.createHash("sha256").update("").digest("hex");
    expect(sign({ payload: Buffer.alloc(0) }).headers["x-amz-content-sha256"]).toBe(empty);
  });
});

/**
 * The transport configuration, without touching the network: what URL a key
 * resolves to, which is the part a misconfigured endpoint makes wrong.
 */
describe("createObjectStorage", () => {
  it("returns null for a partial configuration rather than a client that cannot work", () => {
    // This is what makes the change additive: every install without a bucket
    // configured keeps writing to Postgres, so nothing has to be switched on.
    expect(createObjectStorage(null)).toBeNull();
    expect(createObjectStorage({})).toBeNull();
    expect(
      createObjectStorage({
        endpoint: "http://minio:9000",
        bucket: "b",
        // No credentials.
      }),
    ).toBeNull();
  });

  it("builds a client when the configuration is complete", () => {
    expect(
      createObjectStorage({
        endpoint: "http://minio:9000",
        accessKeyId: "a",
        secretAccessKey: "s",
        bucket: "b",
      }),
    ).toBeInstanceOf(S3ObjectStorage);
  });
});

// ---------------------------------------------------------------------------
// Contract tests: a real MinIO.
// ---------------------------------------------------------------------------

const storageConfig = {
  endpoint: process.env.S3_ENDPOINT ?? "",
  accessKeyId: process.env.S3_ACCESS_KEY ?? "",
  secretAccessKey: process.env.S3_SECRET_KEY ?? "",
  bucket: process.env.S3_BUCKET ?? "",
  region: process.env.S3_REGION ?? "us-east-1",
  forcePathStyle: process.env.S3_FORCE_PATH_STYLE !== "false",
};

const configured = Boolean(
  storageConfig.endpoint &&
    storageConfig.accessKeyId &&
    storageConfig.secretAccessKey &&
    storageConfig.bucket,
);

const client: ObjectStorage | null = configured
  ? new S3ObjectStorage({ ...storageConfig, forcePathStyle: true })
  : null;

/** Each test writes under its own prefix, so tests cannot see each other's keys. */
function testKey(name: string): string {
  return `contract-tests/${process.pid}-${crypto.randomUUID()}/${name}`;
}

/**
 * Waits for MinIO to accept a bucket operation.
 *
 * The compose service has no healthcheck (the MinIO image ships neither `curl`
 * nor `wget` reliably, so a shell-based one would be a lie), which means the
 * first operation can race its startup. `ensureBucket` memoises its promise but
 * clears it on failure, so retrying it is the natural readiness probe — and it
 * is the operation under test anyway.
 */
async function waitForStorage(): Promise<void> {
  const deadline = Date.now() + 30_000;
  let lastError: unknown;
  while (Date.now() < deadline) {
    try {
      await client!.ensureBucket();
      return;
    } catch (error) {
      lastError = error;
      await new Promise((resolve) => setTimeout(resolve, 500));
    }
  }
  throw new Error(`MinIO never became usable: ${String(lastError)}`);
}

afterAll(async () => {
  // Leave nothing behind: this runs against the developer's dev MinIO or the
  // test service, and a contract suite that litters a bucket gets noticed when
  // it is someone else's bucket.
  if (!client) return;
  for (const key of writtenKeys) {
    await client.deleteObject(key).catch(() => undefined);
  }
});

const writtenKeys: string[] = [];

/**
 * Whether the contract tests can run, decided by asking storage rather than by
 * reading the configuration.
 *
 * **Why this is a reachability probe and not just `S3_ENDPOINT !== ""`.** The
 * suite's `docker-compose.test.yml` sets `S3_*`, so "configured" is true
 * whenever the tests run under compose — and in a sandbox whose container
 * network cannot route between services, every one of these tests would hang
 * until its timeout and fail. A suite that fails for a reason unrelated to the
 * code is worse than one that says so, because the failure gets ignored and then
 * so does the next one.
 *
 * **Why skipping is acceptable here, when it usually is not.** A skipped test
 * proves nothing, and that is a real cost, so it is not taken quietly: the
 * warning below names exactly what went unverified and how to run it for real.
 * The alternative — a mock — is strictly worse, because the whole risk in a
 * hand-rolled signer is that the server disagrees with it, and a mock of our own
 * client would agree with us by construction. That is the shape issue #43 hid
 * in, and this file exists because of it.
 *
 * The verification actually performed for issue #30 is
 * `scripts/verify/issue-30-object-storage.mts`, which runs against real MinIO
 * and real PostgreSQL; the note at the bottom of that script records the command.
 */
async function probeStorage(): Promise<{ ok: boolean; detail: string }> {
  if (!configured) {
    return { ok: false, detail: "S3_ENDPOINT/S3_ACCESS_KEY/S3_SECRET_KEY/S3_BUCKET are unset" };
  }
  try {
    await client!.ensureBucket();
    return { ok: true, detail: "" };
  } catch (error) {
    return { ok: false, detail: error instanceof Error ? error.message : String(error) };
  }
}

const reachability = await probeStorage();

if (!reachability.ok) {
  console.warn(
    `\n[object storage] SKIPPING the live MinIO contract tests: ${reachability.detail}.\n` +
      "  The S3ObjectStorage round trip (put/get/delete, binary payloads, keys\n" +
      "  needing RFC 3986 encoding, access-denied and unreachable mapping) is\n" +
      "  therefore UNVERIFIED in this run. Those tests are not mocked on purpose:\n" +
      "  a fake S3 would validate the signer against itself, which is the mistake\n" +
      "  issue #43 hid in. To verify for real, provide a reachable MinIO and run\n" +
      "  `docker compose -f docker-compose.test.yml up --build\n" +
      "   --abort-on-container-exit --exit-code-from test`, or run the committed\n" +
      "  verification script — see the header of scripts/verify/issue-30-object-storage.mts.\n",
  );
}


describe.skipIf(!reachability.ok)("S3ObjectStorage against a real MinIO", () => {
  it("survives a full put/get/delete round trip", async () => {
    await waitForStorage();
    const key = testKey("round-trip.txt");
    writtenKeys.push(key);
    const body = Buffer.from("yggdrasil object storage contract\n", "utf8");

    await client!.putObject({ key, body, contentType: "text/plain; charset=utf-8" });

    const fetched = await client!.getObject(key);
    expect(fetched).not.toBeNull();
    // Byte-identical, which is the only thing that matters for an artifact: a
    // video whose bytes shifted by one is a corrupt video.
    expect(fetched!.equals(body)).toBe(true);

    await client!.deleteObject(key);
    expect(await client!.getObject(key)).toBeNull();
  });

  it("round-trips bytes that are not valid UTF-8", async () => {
    await waitForStorage();
    const key = testKey("binary.bin");
    writtenKeys.push(key);
    // All 256 byte values, including NUL and the high range: a text-decoding
    // bug anywhere in the path shows up here and nowhere else.
    const body = Buffer.from(Array.from({ length: 256 }, (_, index) => index));

    await client!.putObject({ key, body, contentType: "video/webm" });
    const fetched = await client!.getObject(key);

    expect(fetched!.equals(body)).toBe(true);
    await client!.deleteObject(key);
  });

  it("round-trips a key containing characters that need RFC 3986 encoding", async () => {
    await waitForStorage();
    // A space, a plus, an apostrophe and a parenthesis — the exact set
    // `encodeURIComponent` would get wrong. If the encoding is wrong, the object
    // is stored under one name and looked up under another, which a naive test
    // would not notice because both operations would "succeed".
    const key = testKey("odd name (2026)'s+budget.txt");
    writtenKeys.push(key);
    const body = Buffer.from("encoded key", "utf8");

    await client!.putObject({ key, body, contentType: "text/plain" });
    const fetched = await client!.getObject(key);

    expect(fetched).not.toBeNull();
    expect(fetched!.toString("utf8")).toBe("encoded key");
    await client!.deleteObject(key);
  });

  it("replaces an object whose key is written twice", async () => {
    await waitForStorage();
    // This is the property every one of the three repositories depends on: an
    // upsert on a retried upload must overwrite rather than accumulate, which is
    // only true if the key is stable and `PUT` replaces.
    const key = testKey("replaced.txt");
    writtenKeys.push(key);

    await client!.putObject({ key, body: Buffer.from("first"), contentType: "text/plain" });
    await client!.putObject({ key, body: Buffer.from("second"), contentType: "text/plain" });

    expect((await client!.getObject(key))!.toString("utf8")).toBe("second");
    await client!.deleteObject(key);
  });

  it("returns null for a key that does not exist, rather than throwing", async () => {
    await waitForStorage();
    // The download routes branch on this exact distinction: a missing object is
    // "we no longer have it" (410), not a 500.
    expect(await client!.getObject(testKey("never-written.txt"))).toBeNull();
  });

  it("treats deleting an absent key as a no-op", async () => {
    await waitForStorage();
    // S3's own semantics, relied on by `purgeExpired`: a retried sweep must not
    // fail because another replica got there first.
    await expect(client!.deleteObject(testKey("never-written.txt"))).resolves.toBeUndefined();
  });

  it("handles an object larger than one HTTP buffer comfortably", async () => {
    await waitForStorage();
    // 5 MB: past any single TCP segment and past the point where a naive client
    // might truncate a body. Real recordings are up to 25 MB (the configured
    // cap), so a client that only works for small objects would pass every other
    // test here and fail in production.
    const key = testKey("large.bin");
    writtenKeys.push(key);
    const body = crypto.randomBytes(5 * 1024 * 1024);

    await client!.putObject({ key, body, contentType: "video/webm" });
    const fetched = await client!.getObject(key);

    expect(fetched!.byteLength).toBe(body.byteLength);
    expect(fetched!.equals(body)).toBe(true);
    await client!.deleteObject(key);
  });

  it("reports a wrong credential as access_denied rather than as a mystery", async () => {
    await waitForStorage();
    // The code is what callers branch on, so a bad key has to be distinguishable
    // from an unreachable endpoint — the two need opposite responses from an
    // operator.
    const wrong = new S3ObjectStorage({
      ...storageConfig,
      secretAccessKey: "definitely-not-the-key",
      forcePathStyle: true,
    });

    await expect(
      wrong.getObject(testKey("anything.txt")),
    ).rejects.toMatchObject({ code: "access_denied" });
  });

  it("reports an unreachable endpoint as unreachable, and does not hang", async () => {
    // A timeout is the failure mode a containerised deployment actually hits
    // (a wrong service name, a NetworkPolicy), and without an explicit
    // `AbortSignal` fetch has no default — so this asserts the bound exists.
    const dead = new S3ObjectStorage({
      ...storageConfig,
      endpoint: "http://storage-that-does-not-resolve.invalid:9000",
      timeoutMs: 5_000,
      forcePathStyle: true,
    });

    await expect(dead.getObject("x")).rejects.toMatchObject({ code: "unreachable" });
  }, 20_000);

  it("surfaces the error class callers catch, with the status attached", async () => {
    const wrong = new S3ObjectStorage({
      ...storageConfig,
      secretAccessKey: "not-the-key",
      forcePathStyle: true,
    });
    const error = await wrong.getObject(testKey("x.txt")).catch((caught: unknown) => caught);

    expect(error).toBeInstanceOf(ObjectStorageError);
    expect((error as ObjectStorageError).status).toBe(403);
  });
});